xodio/xod

- packages/xod-client/src/core/styles/components/Comment.scss
- packages/xod-client/src/editor/containers/Patch.jsx
- packages/xod-client/src/project/components/Comment.jsx
> Fix Comment text positioning issues

- packages/xod-client-browser/src/components/PopupInstallApp.jsx
- packages/xod-client/src/core/styles/components/Button.scss
> IDE download button

- packages/xod-arduino-deploy/src/boardsParser.js
- packages/xod-arduino-deploy/src/packageIndex.json
- packages/xod-arduino-deploy/src/utils.js
- packages/xod-arduino-deploy/test/boardsParser.spec.js
- packages/xod-arduino-deploy/test/fixtures/packages/arduino/hardware/avr/boards.txt
- packages/xod-arduino-deploy/test/utils.spec.js
- packages/xod-client-electron/src/app/arduinoActions.js
- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
- packages/xod-fs/test/loadSave.spec.js
> Fix compiling and uploading to boards with multiple cpu variants (like Arduino Nano)

- packages/xod-arduino-deploy/src/packageIndex.json
> chore(xod-arduino-deploy): extend package index with PlatformIO board IDs

- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/LabelWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
> feat(xod-client): add tooltips for unlabeled fields/buttons in ProjectBrowser and Inspector

- packages/xod-arduino/platform/program.tpl.cpp
- packages/xod-arduino/platform/runtime.cpp
- packages/xod-arduino/src/templates.js
- packages/xod-arduino/src/transpiler.js
- packages/xod-arduino/src/types.js
- packages/xod-arduino/test/fixtures/program.cpp
- packages/xod-arduino/test/templates.spec.js
- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-arduino/tools/test-avr-size.sh
- packages/xod-client-electron/test-func/fixtures/blink.cpp
- packages/xod-client/src/editor/containers/Tabs.jsx
- packages/xod-client/src/utils/array.js
- packages/xod-func-tools/src/index.js
- packages/xod-project/src/index.js
- packages/xod-project/src/patch.js
- packages/xod-project/test/patch.spec.js
- workspace/blink/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/two-button-switch/__fixtures__/arduino.cpp
> Get rid of topology indirection layer in generated C++

- packages/xod-client-electron/src/view/containers/App.jsx
> Make help menu last in desktop IDE

- package.json
- packages/xod-client-browser/webpack.config.js
- packages/xod-client-electron/.babelrc
- packages/xod-client/.babelrc
- packages/xod-client/src/core/styles/components/Node.scss
- packages/xod-client/src/editor/components/PatchDocs.jsx
- packages/xod-client/src/project/components/Node.jsx
- packages/xod-client/stories/PatchDocs.jsx
- yarn.lock
> Outstanding look for terminal nodes ✨

- packages/xod-client/src/core/styles/components/PatchGroupItem.scss
- packages/xod-client/src/projectBrowser/components/PatchGroupItem.jsx
> Make PatchGroupItem’s label handle click events

- CHANGELOG.md
- docs/tutorial/data-types-and-conversions/README.md
- docs/tutorial/nodes-and-links/README.md
Bump changelog, mention new features.
> Docs update for v0.13.0

- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/editor/components/PatchInspector.jsx
- packages/xod-client/src/editor/containers/Tabs.jsx
- packages/xod-client/src/editor/reducer.js
Closes #756
Closes #758
Closes #757
Also fixes error when creating a new patch while a node is selected
> Fix errors related to tab switching

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-patch-search/test/index.spec.js
- packages/xod-project/package.json
- workspace/lib/xod/common-hardware/project.xod
- workspace/lib/xod/core/project.xod
A formal PR, part of the [release process](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).
> Release 0.13.0

- packages/xod-cli/src/xodc.js
> Make default PM url points to production server

- packages/xod-arduino/platform/runtime.cpp
- packages/xod-client-electron/test-func/fixtures/blink.cpp
- workspace/blink/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/lib/xod/core/and/patch.xodp
- workspace/lib/xod/core/equal/patch.xodp
- workspace/lib/xod/core/greater/patch.xodp
- workspace/lib/xod/core/less/patch.xodp
- workspace/lib/xod/core/nand/patch.xodp
- workspace/lib/xod/core/pwm-output/patch.xodp
- workspace/lib/xod/core/system-time/patch.xodp
- workspace/two-button-switch/__fixtures__/arduino.cpp
> Erradicate a repeating typo

- packages/xod-arduino-deploy/src/serialport.js
- packages/xod-deploy/src/serialport.js
> Fix upload modal gets stuck when serial port is busy

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-project/package.json
- workspace/lib/xod/common-hardware/project.xod
- workspace/lib/xod/core/project.xod
The PR is a part of the [standard release cycle](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).
> Release 0.14.0

- packages/xod-client/src/editor/containers/Patch/index.jsx
- packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
- packages/xod-client/src/project/components/Node.jsx
- packages/xod-client/src/project/components/layers/NodesLayer.jsx
I can't find out the issue, but I think this is a good tweak :)
(It's not about drilling down while debug session is active)
> Drill down into patch on double click on the Node

- packages/xod-client-electron/src/upload/components/PopupUploadProject.jsx
- packages/xod-client/src/core/styles/components/Modals.scss
- packages/xod-client/src/core/styles/components/SkyLight.scss
The only exception is the upload log.
> Disable text selection in modals

- packages/xod-client/src/editor/containers/Patch/modes/acceptingDraggedPatch.jsx
- packages/xod-client/src/editor/containers/Patch/modes/linking.jsx
- packages/xod-client/src/editor/containers/Patch/modes/moving.jsx
- packages/xod-client/src/editor/containers/Patch/modes/panning.jsx
- packages/xod-client/src/editor/containers/Patch/modes/resizingComment.jsx
Closes #811
Also fixes a bug where hotkeys could be inactive after editor mode change
> Cancel linking on esc

- packages/xod-client-electron/test-func/suite.spec.js
- packages/xod-client/src/editor/containers/Patch/index.jsx
- packages/xod-client/src/editor/selectors.js
- packages/xod-client/src/project/selectors.js
> fix(xod-client): fix error when closing last opened tab

- packages/xod-client-electron/test-func/pageObject.js
- packages/xod-client-electron/test-func/suite.spec.js
- packages/xod-client/src/editor/reducer.js
- packages/xod-client/src/projectBrowser/actions.js
> Fix crashing of IDE on patch delete

- packages/xod-client/src/core/styles/components/TabsItem.scss
- packages/xod-client/src/editor/containers/Tabs.jsx
> Fix tab sorting

- packages/xod-client/src/editor/reducer.js
Bug crashes IDE when User tried to rename current patch.
Fixed without issue 😬
> Fix: renaming of patch path crashes IDE when debug session is active

- .eslintrc.js
- packages/xod-client-browser/webpack.config.js
- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client-electron/webpack.config.js
- packages/xod-client/README.md
- packages/xod-client/package.json
- packages/xod-client/src/core/actions.js
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/core/reducer.js
- packages/xod-client/src/core/selectors.js
- packages/xod-client/src/core/state.js
- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/index.js
- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
- packages/xod-client/src/user/actionTypes.js
- packages/xod-client/src/user/actions.js
- packages/xod-client/src/user/reducer.js
- packages/xod-client/src/user/selectors.js
- packages/xod-client/src/user/state.js
- packages/xod-client/src/utils/urls.js
- yarn.lock
> Display compilation limits

- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/user/actions.js
> Set `x-launch` header for compilation limit request on IDE startup

- packages/xod-client/src/project/selectors.js
- packages/xod-client/src/project/utils.js
- packages/xod-client/src/projectBrowser/selectors.js
> Don’t allow manually placing xod/patch-nodes/*-dead nodes

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/core/project.xod
The PR is a part of the [release process](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).
> Release 0.15.0

- CHANGELOG.md
- lerna.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- workspace/__lib__/xod/core/project.xod
Part of the [release process](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).
> Release 0.15.1

- packages/xod-client/src/editor/reducer.js
> Guarantee to open the first patch with correct offset when opening a project

- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/editor/containers/Editor.jsx
- packages/xod-client/src/editor/containers/Patch/modes/debugging.jsx
- packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
- packages/xod-client/src/utils/browser.js
> Fix breaking copy paste after inputs interaction

- packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
- packages/xod-client/src/project/nodeLayout.js
> Fix positioning of new nodes via double-click on patch

- packages/xod-client/package.json
- packages/xod-client/src/core/styles/components/MarqueeSelection.scss
- packages/xod-client/src/core/styles/main.scss
- packages/xod-client/src/editor/constants.js
- packages/xod-client/src/editor/containers/Patch/index.jsx
- packages/xod-client/src/editor/containers/Patch/modes/linking.jsx
- packages/xod-client/src/editor/containers/Patch/modes/marqueeSelecting.jsx
- packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
- packages/xod-client/src/editor/marqueeGeometry.js
- packages/xod-client/src/editor/reducer.js
- packages/xod-client/src/editor/utils.js
- packages/xod-client/src/project/components/layers/BackgroundLayer.jsx
- packages/xod-client/test/marqueeGeometry.spec.js
- packages/xod-func-tools/src/index.js
- yarn.lock
It closes #820.
On preview:
Black circle — just left click
Red circle — left click + cmd (or ctrl)
> Add multiple selection with marquee

- packages/xod-client/src/project/reducer.js
> Make default comment wider

- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/editor/utils.js
- packages/xod-client/src/project/nodeLayout.js
> If pasted entities are the same as selected, paste them with just a little offset

- .gitattributes
- docs/reference/supported-hardware/index.yaml
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/LiquidCrystal_I2C.cpp
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/LiquidCrystal_I2C.h
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/README.md
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/examples/BlinkingCursor/BlinkingCursor.ino
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/examples/CustomChars/CustomChars.ino
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/examples/HelloWorld/HelloWorld.ino
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/examples/SerialDisplay/SerialDisplay.ino
- packages/xod-client-electron/arduino-libraries/LiquidCrystal_I2C/keywords.txt
- packages/xod-client-electron/arduino-libraries/README.md
- workspace/__lib__/xod/common-hardware/text-lcd-16x2-i2c/arduino.cpp
- workspace/__lib__/xod/common-hardware/text-lcd-16x2-i2c/patch.xodp
> Implement text-lcd-16x2-i2c

- workspace/__lib__/xod/core/log-10/any.cpp
- workspace/__lib__/xod/core/log-10/patch.xodp
- workspace/__lib__/xod/core/log-bx/patch.xodp
- workspace/__lib__/xod/core/log-e/any.cpp
- workspace/__lib__/xod/core/log-e/patch.xodp
Logarithms are necessary :neckbeard:
> Add logarithm nodes

- packages/xod-arduino-deploy/src/packageIndex.json
- packages/xod-arduino-deploy/src/uploader.js
- packages/xod-arduino-deploy/src/utils.js
- packages/xod-arduino-deploy/test/upload.spec.js
- packages/xod-arduino-deploy/test/utils.spec.js
- packages/xod-client-electron/src/app/arduinoActions.js
- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
There is no issue, but it fixes [forum report](https://forum.xod.io/t/help-with-upload-to-arduino/166/6).
> Fix local upload to Arduino Mega 2560 (and possibly others)

- docs/reference/supported-hardware/index.yaml
- workspace/__lib__/xod/common-hardware/dht11-thermometer/patch.xodp
- workspace/__lib__/xod/common-hardware/dht2x-pack/patch.xodp
- workspace/__lib__/xod/common-hardware/dht2x-thermometer/patch.xodp
- workspace/__lib__/xod/common-hardware/dhtxx-read-raw/patch.cpp
- workspace/__lib__/xod/common-hardware/dhtxx-read-raw/patch.xodp
DHT11 has awful ±2°C precision. Although it is very cheap :grimacing: 
This PR generalizes our library to support reading more accurate sensors DHT21, DHT22 and their friends.
> Support for DHT21 and higher thermometers

- packages/xod-project/src/pin.js
- packages/xod-project/test/pin.spec.js
- workspace/__lib__/xod/core/duty-to-time/patch.xodp
- workspace/__lib__/xod/core/flip-n-times/patch.xodp
- workspace/__lib__/xod/core/modulo/patch.cpp
- workspace/__lib__/xod/core/modulo/patch.xodp
- workspace/__lib__/xod/core/saw-wave-map/patch.xodp
- workspace/__lib__/xod/core/saw-wave/patch.xodp
- workspace/__lib__/xod/core/sine-wave-map/patch.xodp
- workspace/__lib__/xod/core/sine-wave/patch.xodp
- workspace/__lib__/xod/core/square-wave/patch.cpp
- workspace/__lib__/xod/core/square-wave/patch.xodp
- workspace/__lib__/xod/core/time-to-duty/patch.xodp
- workspace/__lib__/xod/core/timer/patch.cpp
- workspace/__lib__/xod/core/timer/patch.xodp
- workspace/__lib__/xod/core/tri-wave-map/patch.xodp
- workspace/__lib__/xod/core/tri-wave/patch.xodp
The nodes introduced are listed in the commit message body.
> Tweak pin numbering scheme, add time-signal generation nodes

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
The main rationale is routing feature requests to the forum for discussions.
> Actualize contributing policies and templates

- packages/xod-project/src/flatten.js
- packages/xod-project/test/fixtures/bound-values-propagation-to-busy-output.flat.json
- packages/xod-project/test/fixtures/bound-values-propagation-to-busy-output.xodball.json
- packages/xod-project/test/flatten.spec.js
No issue 😬
See [this xodball](https://gist.github.com/evgenykochetkov/ce828868a657f7bfd529631a96f88cac) for a minimal example
> Don’t propagate bound values to occupied outputs

- packages/xod-client-electron/test-func/0-fs.spec.js
- packages/xod-client-electron/test-func/1-blink.spec.js
- packages/xod-client-electron/test-func/pageObject.js
- packages/xod-client/src/editor/containers/Editor.jsx
> Fix crash when deleting opened patch

- .eslintrc.js
- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/src/app/main.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client-electron/test-func/pageObject.js
- packages/xod-client/package.json
- packages/xod-client/src/core/components/Button.jsx
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/core/styles/components/AccountPane.scss
- packages/xod-client/src/core/styles/main.scss
- packages/xod-client/src/editor/containers/Editor.jsx
- packages/xod-client/src/user/actionTypes.js
- packages/xod-client/src/user/actions.js
- packages/xod-client/src/user/components/AuthForm.jsx
- packages/xod-client/src/user/containers/AccountPane.jsx
- packages/xod-client/src/user/messages.js
- packages/xod-client/src/user/reducer.js
- packages/xod-client/src/user/selectors.js
- packages/xod-client/src/user/state.js
- packages/xod-client/src/utils/menu.js
- packages/xod-client/src/utils/urls.js
- yarn.lock
> Add account pane

- packages/xod-client/src/project/components/PopupProjectPreferences.jsx
- packages/xod-fs/src/save.js
> Fix saving and editing project meta data

- package.json
- packages/xod-client/src/project/resolveLibsMiddleware.js
- yarn.lock
There is no issue, but it relates to PR #907 and issue #874
> Fix auto resolving libraries on import xodball

- .circleci/config.yml
- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
The PR is a part of the [release process](https://github.com/xodio/xod/wiki/Releasing-a-New-Version)
> Release 0.16.0

- packages/xod-pm/test-func/fetch.spec.js
This is just a quick fix, the fact that dependencies are hardcoded is still an issue 😬
> Fix failing functional test

- packages/xod-client/src/user/components/AuthForm.jsx
> Submit auth form by pressing ENTER key

- packages/xod-client/src/core/styles/components/CppImplementationEditor.scss
- packages/xod-client/src/editor/components/CppImplementationEditor.jsx
> Fix code editor styles to fit window and scrolls normally

- packages/xod-client/src/user/actions.js
> Logout without connection shows error message

- packages/xod-client/package.json
- packages/xod-client/src/editor/components/Suggester.jsx
> Escape quick search queries

- docs/README.md
- docs/guide/nodes-for-xod-in-xod/README.md
- docs/reference/README.md
> Fix links in documentation

- packages/xod-client/src/editor/containers/Patch/dropTarget.js
- packages/xod-client/src/editor/containers/Patch/index.jsx
> Return Patch component to default mode when patch from project browser was dragged out

- packages/xod-client/src/editor/components/LibSuggester.jsx
> Refresh library search after pasting

- workspace/__lib__/xod/core/pulse-on-false/patch.xodp
> Fix description of pulse-on-false

- packages/xod-pm/src/fetch.js
> Fix infinite retries while fetching lib datas / libs

- packages/xod-client/src/core/assets/icons/back.svg
- packages/xod-client/src/core/styles/abstracts/colors.scss
- packages/xod-client/src/core/styles/components/Breadcrumbs.scss
- packages/xod-client/src/core/styles/components/CodeMirror.scss
- packages/xod-client/src/core/styles/components/CppImplementationEditor.scss
- packages/xod-client/src/core/styles/components/Debugger.scss
- packages/xod-client/src/core/styles/main.scss
- packages/xod-client/src/debugger/containers/Breadcrumbs.jsx
- packages/xod-client/src/editor/components/CppImplementationEditor.jsx
- packages/xod-client/src/editor/containers/Editor.jsx
> Update Breadcrumbs and CodeEditor styles

- CHANGELOG.md
* [ide] General user interface facelift. Updated icons, reduced visual noise, more accurate accents. Better messages and the main menu.
* [ide] Make panels dockable. Now you can tweak location of any sidebar panel: dock it to the left or right, hide, resize.
* [ide] The project browser, quick search suggester, and selected node got own help boxes. All available with H key as it was before.
* [ide] Introduce deploy pane. Now all output during upload and debug messages go here.
* [ide] Improve syntax highlighting in the embedded code editor. Match XOD C++ node API symbols, inttypes, and few Arduino built-in functions.
* [nodes] Fix wrong description of `xod/core/pulse-on-false` (thanks @awgrover)
> Update changelog for upcoming 0.17.0

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/core/project.xod
> Release 0.17.0

- packages/xod-client/src/core/styles/components/PatchDocs.scss
> Fix content min-width in Quick Help panel

- packages/xod-client-electron/src/view/styles/components/PopupProjectSelection.scss
- packages/xod-client/src/core/styles/base/base.scss
- packages/xod-client/src/core/styles/components/PatchGroup.scss
- packages/xod-client/src/core/styles/components/PatchGroupItem.scss
> Fix cursor shapes for some elements

- CHANGELOG.md
* [ide] Fix help panel content overflow.
* [ide] Fix quick search help box text moire (best noticable on Windows).
* [ide] Fix background size for a view when no patches are open.
* [ide] Fix cursor shapes for various UI elements.
* [ide] Fix long lines truncation in the deployment log.
* [ide] Fix aliasing of IDE desktop icon on Windows.
> Update changelog for the 0.17.1

- CHANGELOG.md
- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
The PR is a part of the [release process](https://github.com/xodio/xod/wiki/Releasing-a-New-Version).
> Release 0.17.1

- packages/xod-client-electron/src/view/containers/App.jsx
[Reported on the forum](https://forum.xod.io/t/typo-in-updater-text/331)
> Fix typo in updater dialog

- packages/xod-arduino/package.json
- packages/xod-arduino/src/templates.js
- packages/xod-arduino/src/transpiler.js
- packages/xod-cli/package.json
- packages/xod-client-electron/package.json
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/package.json
- packages/xod-client/src/core/actions.js
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/debugger/selectors.js
- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/editor/containers/Editor.jsx
- packages/xod-client/src/editor/containers/Patch/index.jsx
- packages/xod-client/src/editor/containers/Tabs.jsx
- packages/xod-client/src/editor/messages.js
- packages/xod-client/src/editor/selectors.js
- packages/xod-client/src/project/actions.js
- packages/xod-client/src/project/components/Pin.jsx
- packages/xod-client/src/project/selectors.js
- packages/xod-client/src/project/utils.js
- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
- packages/xod-fs/package.json
- packages/xod-fs/src/types.js
- packages/xod-func-tools/package.json
- packages/xod-func-tools/src/monads.js
- packages/xod-func-tools/src/types.js
- packages/xod-func-tools/test/lists.spec.js
- packages/xod-project/package.json
- packages/xod-project/src/link.js
- yarn.lock
> Update `sanctuary-def` dependency to v0.14.0

- packages/xod-client/src/editor/reducer.js
> Preserve patch offset when starting debugger

- packages/xod-client-browser/test-func/creatingBlinkPatch.spec.js
- packages/xod-client-electron/test-func/pageObject.js
- packages/xod-client/src/core/styles/abstracts/variables.scss
- packages/xod-client/src/core/styles/components/AccountPane.scss
- packages/xod-client/src/core/styles/components/CodeMirror.scss
- packages/xod-client/src/core/styles/components/HelpPanel.scss
- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/core/styles/components/PatchDocs.scss
- packages/xod-client/src/core/styles/components/SkyLight.scss
- packages/xod-client/src/core/styles/components/SnackBarMessage.scss
- packages/xod-client/src/core/styles/components/Suggester.scss
- packages/xod-client/src/core/styles/components/TabsItem.scss
- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/editor/components/PatchInspector.jsx
It closes #1002.
Also, basic font sizes were changed to 8/10/12/16px. `xl` size was removed.
> Update and unify basic styles

- packages/xod-client/src/core/styles/components/PatchSVG.scss
- packages/xod-client/src/editor/containers/Patch/modes/panning.jsx
> Fix panning mode: show grab cursors and disable hovering of Patch contents

- packages/xod-client/src/core/styles/components/Breadcrumbs.scss
- packages/xod-client/src/core/styles/components/Debugger.scss
- packages/xod-client/src/debugger/containers/Breadcrumbs.jsx
- packages/xod-client/src/editor/containers/Editor.jsx
> Prevent overlaping of Patch contents by Breadcrumbs

- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-browser/test-func/creatingBlinkPatch.spec.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client-electron/test-func/0-fs.spec.js
- packages/xod-client/src/utils/menu.js
No issue, few minor fixes:
- Apply Proper Case to Menu Items
- Add an ellipsis to menu items which open a dialog
- Add “File → Exit” for Linux and Windows
> Make main menu items consistent, follow OS guidelines

- packages/xod-client-electron/src/app/main.js
Regression appeared in my latest PR #1050 😬
> Fix opening projects by double click in FS

- docs/reference/supported-hardware/index.yaml
- workspace/__lib__/xod/common-hardware/ds18b20-thermometer/patch.cpp
- workspace/__lib__/xod/common-hardware/ds18b20-thermometer/patch.xodp
- workspace/__lib__/xod/core/delta-time/patch.xodp
- workspace/__lib__/xod/core/delta/patch.cpp
- workspace/__lib__/xod/core/delta/patch.xodp
- workspace/__lib__/xod/core/duty-to-time/patch.xodp
- workspace/__lib__/xod/core/i2c-request/patch.cpp
- workspace/__lib__/xod/core/pi/patch.xodp
- workspace/__lib__/xod/core/pid-controller/patch.xodp
- workspace/__lib__/xod/core/pulse-on-false/patch.xodp
- workspace/__lib__/xod/core/saw-wave-map/patch.xodp
- workspace/__lib__/xod/core/time-to-duty/patch.xodp
The nodes are cherry-picked from `nkrkv/xxx` libs since they are quite general to be useful in the stdlib.
> Add nodes for a PID controller and DS18B20 thermometer

- packages/xod-client-electron/src/app/workspaceActions.js
- packages/xod-fs/src/find.js
- packages/xod-fs/src/index.js
- packages/xod-fs/src/load.js
But it's a bug produced by me in PR #1050.
Now it fixes a project path, that stored in the state and saves project correctly.
> Fix saving of projects

- packages/xod-client-electron/src/view/nativeDialogs.js
- Make unified UI on Win/Linux platforms.
- Completes PR #1050.
> Fix save/open dialog extensions

- packages/xod-fs/src/save.js
Fixes error:
When trying to save the project as a xodball file — it told "Project saved", but it's not.
Appeared in some of PRs after #1050. 😬
> Fix save Project as xodball

- packages/xod-client-electron/package.json
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client-electron/test-func/0-fs.spec.js
- packages/xod-client-electron/test-func/pageObject.js
- packages/xod-fs/src/save.js
> Fix save of project.xod file in changed project

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
> Release 0.18.0

- CHANGELOG.md
- lerna.json
- packages/xod-client-electron/package.json
> Release 0.18.1

- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-client/package.json
- packages/xod-client/src/core/styles/components/Link.scss
- packages/xod-client/src/core/styles/components/Pin.scss
- packages/xod-client/src/editor/containers/Patch/modes/moving.jsx
- packages/xod-client/src/project/components/Link.jsx
- packages/xod-client/src/project/components/Pin.jsx
- packages/xod-client/src/project/components/layers/LinksLayer.jsx
- packages/xod-client/src/project/nodeLayout.js
- packages/xod-client/src/project/reducer.js
- packages/xod-client/src/project/selectors.js
- packages/xod-client/src/utils/vectors.js
- packages/xod-project/src/index.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/pin.js
- packages/xod-project/src/project.js
- packages/xod-project/test/fixtures/variadics.xodball
- packages/xod-project/test/helpers.js
- packages/xod-project/test/pin.spec.js
- packages/xod-project/test/project.spec.js
- yarn.lock
> Render variadic pins and allow to link them

- packages/xod-project/src/patch.js
- packages/xod-project/test/project.spec.js
Bug created by me in the #1066. 😬
> Fix rendering of one superfluous variadic group

- packages/xod-patch-search/test/index.spec.js
- packages/xod-project/src/expandVariadicNodes.js
- packages/xod-project/test/fixtures/expanding.expected.xodball
- workspace/__lib__/xod/bits/bitwise-and/patch.xodp
- workspace/__lib__/xod/bits/bitwise-or/patch.xodp
- workspace/__lib__/xod/bits/bitwise-xor/patch.xodp
- workspace/__lib__/xod/core/add/patch.cpp
- workspace/__lib__/xod/core/add/patch.xodp
- workspace/__lib__/xod/core/and/patch.cpp
- workspace/__lib__/xod/core/and/patch.xodp
- workspace/__lib__/xod/core/any/patch.cpp
- workspace/__lib__/xod/core/any/patch.xodp
- workspace/__lib__/xod/core/concat/patch.cpp
- workspace/__lib__/xod/core/concat/patch.xodp
- workspace/__lib__/xod/core/discretize/patch.xodp
- workspace/__lib__/xod/core/multiply/patch.cpp
- workspace/__lib__/xod/core/multiply/patch.xodp
- workspace/__lib__/xod/core/nand/patch.cpp
- workspace/__lib__/xod/core/nand/patch.xodp
- workspace/__lib__/xod/core/nor/patch.cpp
- workspace/__lib__/xod/core/nor/patch.xodp
- workspace/__lib__/xod/core/nth-number/patch.xodp
- workspace/__lib__/xod/core/or/patch.cpp
- workspace/__lib__/xod/core/or/patch.xodp
- workspace/__lib__/xod/core/select/patch.xodp
- workspace/__lib__/xod/core/subtract/patch.cpp
- workspace/__lib__/xod/core/subtract/patch.xodp
- workspace/__lib__/xod/core/xor/patch.cpp
- workspace/__lib__/xod/core/xor/patch.xodp
Closes #1068
Also fixes a bug introduced in #1089
> Make standard nodes variadic

- workspace/__lib__/xod/core/join/patch.xodp
A useful node per se very useful for illustrative purposes of #1069
> Implement xod/core/join

- packages/xod-client/src/project/components/Node.jsx
But this bug was introduced in the #1096 by me.
> Fix hanging hover effect on Node after moving / drill down and etc

- CHANGELOG.md
* [core] Implement variadic nodes. An ability to have an adjustable number of input pins on a node.
* [nodes] Nodes from the standard library made variadic if applicable: `add`,  `multiply`, `bitwise-*`, `any`, `and`, `or`, `concat`, `discretize`, `select`, and others.
* [ide] Show richer tooltips on node hover. It shows the node label, fully qualified type, and errors if there are any.
* [xod/core/join](https://xod.io/libs/xod/core/join/)
> Update changelog for upcoming 0.19.0

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/core/project.xod
> Release 0.19.0

- docs/guide/creating-variadics/README.md
Based on [feedback from the forum](https://forum.xod.io/t/xod-0-19-0-released-variadic-nodes/540/4).
> Make clarification for variadics article

- packages/xod-project/src/patch.js
> Сheck for dead links more strictly

- CHANGELOG.md
* [nodes] Do not emit an unconditional pulse from `xod/core/defer-pulse` on boot (#1108)
* [nodes] Remove extraneous utility output from `xod/core/discretize` (#1106)
* [core] Fix IDE crashing when opening some patches with dead links (#1111)
> Update changelog for upcoming 0.19.2

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.19.2

- tools/bump-workspace-lib-versions.sh
It's quite handy for release process.
> Add a tool to bump all core lib versions

- packages/xod-client/src/core/styles/abstracts/variables.scss
- packages/xod-client/src/core/styles/components/Link.scss
- packages/xod-client/src/core/styles/components/PatchDocs.scss
- packages/xod-client/src/core/styles/components/Pin.scss
- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/editor/components/PatchDocs.jsx
- packages/xod-client/src/editor/components/PatchInspector.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/index.js
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/DisabledInputWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
- packages/xod-client/src/project/selectors.js
- packages/xod-project/src/builtInPatches.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/flatten.js
- packages/xod-project/src/index.js
- packages/xod-project/src/messages.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/pin.js
- packages/xod-project/src/project.js
- packages/xod-project/src/utils.js
- packages/xod-project/test/flatten.spec.js
- packages/xod-project/test/patch.spec.js
> Allow to create abstract nodes

- packages/xod-client-electron/package.json
- packages/xod-client-electron/src/app/main.js
- yarn.lock
> Preserve main window geometry across launches

- packages/xod-client/src/editor/components/Suggester.jsx
- packages/xod-patch-search/package.json
- packages/xod-patch-search/src/index.js
- packages/xod-patch-search/test/fixtures/abstract-and-specializations.xodball
- packages/xod-patch-search/test/index.spec.js
> Improve suggester results for abstract and specialization nodes

- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/.npmignore
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/.npmignore
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
There is no issue in this repo.
PR for the website: [Show node preview in library documentation](https://github.com/xodio/services.xod.io/pull/433)
> Add .npmignore and bump package versions for new feature on a website

- packages/xod-client/src/project/components/Pin.jsx
- packages/xod-client/src/project/utils.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/project.js
- packages/xod-project/src/typeDeduction.js
- packages/xod-project/src/types.js
- packages/xod-project/test/typeDeduction.spec.js
A little followup to #1147, necessary for #1122.
> Retain information about conflicting data types in type resolution results

- packages/xod-client/src/editor/containers/Patch/modes/changingArityLevel.jsx
> Fix crash when changing arity level

- packages/xod-arduino/src/transpiler.js
- packages/xod-client/src/core/styles/abstracts/mixins.scss
- packages/xod-client/src/core/styles/components/SnackBarMessage.scss
- packages/xod-client/src/messages/components/SnackBarMessage.jsx
- packages/xod-func-tools/src/errors.js
- packages/xod-project/src/flatten.js
- packages/xod-project/src/messages.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/project.js
- packages/xod-project/test/fixtures/dead-link-deeply.xodball
- packages/xod-project/test/patch.spec.js
- packages/xod-project/test/project.spec.js
> Add patch trace in the Errors

- packages/xod-client/src/editor/reducer.js
Problem was described here: https://github.com/xodio/xod/pull/1150#pullrequestreview-112489916
> Fix crash on pressing undo when nothing was selected

- packages/xod-project/src/flatten.js
- packages/xod-project/test/flatten.spec.js
It relates to #1032.
I forgot to update trace in the `flatten`. 😬
> Add trace to errors in the flatten errors

- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/LabelWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/NodeSpecializationWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
- packages/xod-client/src/project/selectors.js
- packages/xod-client/stories/Inspector.jsx
> Tweak Inspector: Replace node type string with specialization switcher

- packages/xod-arduino/src/templates.js
- packages/xod-client/src/core/styles/abstracts/variables.scss
- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/BoolPinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/NumberPinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PulsePinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
- packages/xod-client/src/utils/inputFormatting.js
- packages/xod-func-tools/src/index.js
- packages/xod-func-tools/src/strings.js
- packages/xod-func-tools/test/strings.spec.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/extractBoundInputsToConstNodes.js
- packages/xod-project/src/index.js
- packages/xod-project/src/legacy.js
- packages/xod-project/src/node.js
- packages/xod-project/test/extractBoundInputsToConstNodes.spec.js
- packages/xod-project/test/legacy.spec.js
- packages/xod-project/test/patch.spec.js
- packages/xod-project/test/project.spec.js
It closes #1158.
Also fixed some minor bug, that dispatches `NODE_PROPERTY_UPDATE` twice.
> Add universal bound literals

- packages/xod-project/src/typeDeduction.js
This should allow to check types while some libraries are missing(for example, if user opened a xodball and some libraries are loading)
> Make deducePinTypes safer

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.20.0

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.20.1

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.20.2

- packages/xod-tabtest/src/TabData.re
- packages/xod-tabtest/src/TabData.rei
- packages/xod-tabtest/src/Tabtest.re
- packages/xod-tabtest/src/XodProject/Pin.re
- packages/xod-tabtest/src/XodProject/Pin.rei
- packages/xod-tabtest/test/TabData_jest.re
- packages/xod-tabtest/workspace/__lib__/xod/tabtest/capture-byte/patch.cpp
- packages/xod-tabtest/workspace/__lib__/xod/tabtest/capture-byte/patch.xodp
- packages/xod-tabtest/workspace/__lib__/xod/tabtest/inject-byte/patch.cpp
- packages/xod-tabtest/workspace/__lib__/xod/tabtest/inject-byte/patch.xodp
- workspace/__lib__/xod/core/if-else(byte)/patch.test.tsv
- workspace/__lib__/xod/core/if-else(number)/patch.test.tsv
> Add support of Byte type in tabular testing

- packages/xod-fs/test/fixtures/some.xodball
- packages/xod-project/src/patch.js
> Sort patch attachments by filename

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/contributing/README.md
For anyone asking how he can help
> Make contributor’s guide

- .circleci/Dockerfile
- .circleci/config.yml
- package.json
- packages/xod-arduino/src/transpiler.js
- packages/xod-client-browser/Dockerfile
- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/src/shared/errorFormatter.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-fs/test/fixtures/some.xodball
- packages/xod-project/Dockerfile
- packages/xod-project/src/legacy.js
- packages/xod-project/src/patch.js
- packages/xod-project/test/legacy.spec.js
A technical PR to keep branches in sync
> Merge 0.20.x back to master

- packages/xod-client/src/project/selectors.js
- packages/xod-func-tools/src/index.js
- packages/xod-func-tools/src/sets.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/typeDeduction.js
Routine port of #1213 back to master
> Merge 0.20.x to master

- .github/ISSUE_TEMPLATE.md
- docs/contributing/README.md
- Fixed grammar and typos
- Duplicated the point about narrowing down a problem in the issue template
> Improve wording for contributing section in the docs

- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/core/crashReporterMiddleware.js
- packages/xod-client/src/core/formatErrorMessage.js
- packages/xod-client/src/core/middlewares.js
- packages/xod-client/src/messages/composeMessage.js
- packages/xod-client/src/messages/formatUnexpectedError.js
- packages/xod-func-tools/src/errors.js
- packages/xod-project/src/messages.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/typeDeduction.js
- packages/xod-project/test/patch.spec.js
- Closes #1220 
- Adds middleware to give user a chance to report unexpected errors
> Fix error reporting

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/core/crashReporterMiddleware.js
- packages/xod-client/src/core/formatErrorMessage.js
- packages/xod-client/src/core/middlewares.js
- packages/xod-client/src/messages/composeMessage.js
- packages/xod-client/src/messages/formatUnexpectedError.js
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-func-tools/src/errors.js
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-project/src/messages.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/typeDeduction.js
- packages/xod-project/test/patch.spec.js
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Chore merge 0.20.x

- packages/xod-client/src/project/selectors.js
> Fix type deduction on changing current patch

- packages/xod-client/src/project/reducer.js
- packages/xod-project/src/typeDeduction.js
> Use default pin values in type deduction

- packages/xod-client/src/core/styles/components/Pin.scss
> Color conflicting pins in the Inspector

- packages/xod-project/src/messages.js
- packages/xod-project/src/typeDeduction.js
> Improve error message about conflicting types

- packages/xod-project/src/messages.js
- packages/xod-project/src/patch.js
- packages/xod-project/src/patchPathUtils.js
- packages/xod-project/src/typeDeduction.js
- packages/xod-project/test/fixtures/custom-types.resolved.xodball
- packages/xod-project/test/fixtures/custom-types.xodball
- packages/xod-project/test/typeDeduction.spec.js
Closes #1190
[custom-types-demo.xodball.zip](https://github.com/xodio/xod/files/2045339/custom-types-demo.xodball.zip)
> Resolve custom types on generics

- docs/README.md
- docs/guide/data-types/README.md
- docs/guide/linking-rules/README.md
- docs/reference/README.md
- docs/reference/data-types/README.md
> Document byte and port types, extract Data Types Reference

- packages/xod-arduino/src/transpiler.js
- packages/xod-arduino/test/fixtures/ensure-custom-types-are-defined.xodball
- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-project/src/index.js
> Make sure definitions for all used custom types are included

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.21.0

- packages/xod-arduino/src/transpiler.js
A tiny refactor that should have been done quite a while ago
> Rename imported 'xod-project' from Project to XP in `xod-arduino`

- packages/xod-arduino/package.json
- packages/xod-client/package.json
- packages/xod-client/test/reducers/editor.spec.js
- packages/xod-client/test/reducers/processes.spec.js
- packages/xod-client/test/state.spec.js
- packages/xod-fs/test/backup.spec.js
- packages/xod-fs/test/load.spec.js
- packages/xod-project/package.json
- packages/xod-project/test/flatten.spec.js
- packages/xod-project/test/gmath.spec.js
- packages/xod-project/test/helpers.js
- packages/xod-project/test/helpers.spec.js
- packages/xod-project/test/link.spec.js
- packages/xod-project/test/node.spec.js
- packages/xod-project/test/patch.spec.js
- packages/xod-project/test/patchPathUtils.spec.js
- packages/xod-project/test/pin.spec.js
- packages/xod-project/test/project.spec.js
- packages/xod-project/test/utils.spec.js
- yarn.lock
> Migrate tests from expect to assert, get rid of dirty-chai

- packages/xod-client-electron/src/app/workspaceActions.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/core/trackLastSavedChanges.js
> Do not update last saved project on "Save as a Copy"

- packages/xod-pm/test-func/fetch.spec.js
> Update expected deps list in func tests

- workspace/__lib__/xod/math/clip/patch.cpp
> Correct output name in xod/math/clip impl

- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-project/src/extractBoundInputsToConstNodes.js
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
> Do not try to extract "stale" bound values

- packages/xod-project/src/flatten.js
- packages/xod-project/test/fixtures/constant-propagation-through-bound-output.flat.xodball
- packages/xod-project/test/fixtures/constant-propagation-through-bound-output.xodball
- packages/xod-project/test/flatten.spec.js
> Allow constant node values to propagate down when flattening

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.21.2

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-project/src/extractBoundInputsToConstNodes.js
- packages/xod-project/src/flatten.js
- packages/xod-project/test/fixtures/constant-propagation-through-bound-output.flat.xodball
- packages/xod-project/test/fixtures/constant-propagation-through-bound-output.xodball
- packages/xod-project/test/flatten.spec.js
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/clip/patch.cpp
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/units/project.xod
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
Merges #1306, #1307, #1308, #1309
> Merge 0.21.x into master

- packages/xod-client/src/editor/utils.js
- packages/xod-client/src/project/nodeLayout.js
> Make computation of bounding boxes safer

- packages/xod-project/src/patch.js
> Always mark pins of custom type as not bindable

- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
> Make library sorting in project browser more intuitive

- packages/xod-client/package.json
- packages/xod-client/src/core/styles/components/ProjectBrowser.scss
- yarn.lock
> Stop long patch names from overflowing

- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/utils/menu.js
> Add toggle items into View menu

- packages/xod-client/src/core/styles/base/base.scss
- packages/xod-client/src/core/styles/components/Debugger.scss
- packages/xod-client/src/core/styles/components/Sidebar.scss
> Get rid of white stripes on zooming

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.22.0

- packages/xod-client/src/project/components/Node.jsx
- packages/xod-client/src/project/components/nodeParts/ConstantNodeBody.jsx
> Show values as labels in constant nodes

- packages/xod-arduino/src/transpiler.js
- packages/xod-arduino/test/transpiler.spec.js
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
> Comment out xod pragmas

- workspace/__lib__/xod/uart/uart/patch.cpp
> Fix UART for boards like Uno

- workspace/__lib__/xod/uart/uart/patch.cpp
Merge `0.22.x` into `master`.
Merges #1382
> Merge 0.22.x with fix of UART for Uno

- packages/xod-project/src/patch.js
There is no issue 😬 
**How to reproduce:**
1. Download xodball (it have dead references and links): [deadrefs.xodball.zip](https://github.com/xodio/xod/files/2274206/deadrefs.xodball.zip)
2. Open Project
3. Create new Patch "b", leave it empty
4. Open "main" patch
CRASH! See console.
> Fix bug with dead reference error

- packages/xod-client/src/project/utils.js
> Fix displaying pins with conflicting types as custom

- packages/xod-patch-search/src/index.js
It reduces search time:
- by ~9% for common searches (like "number", "meter" and etc): 108ms -> 99ms
- by ~54% for search by a library ("lib:xod/core add"): 68ms -> 30ms
- by ~ 91% for search specializations ("when-either-ch(mber"): 74ms -> 6.79ms
- unchanged for search abstracts: 74ms -> 74ms
Also, it exports two new methods: `setCollection` and `getCollection, that will be used in a further optimization.
> Improve performance of `xod-patch-search`

- packages/xod-client/src/hinting/validation.js
- packages/xod-project/src/internal/patchPathUtils.js
- packages/xod-project/src/patchPathUtils.js
> Fix error hinting on bus label change

- CHANGELOG.md
- lerna.json
- packages/holes/package.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.23.0

- packages/xod-client/src/hinting/patchSearchData.js
> Reject deprecated and utility nodes from patch search

- packages/xod-client/src/core/styles/components/Node.scss
- packages/xod-client/src/core/styles/components/TabsItem.scss
- packages/xod-client/src/hinting/patchSearchData.js
Includes fixes from these PRs: #1415 #1416 #1417.
> Merge fixes from 0.23.x into master

- packages/xod-project/src/gmath.js
Massively improves toposorting time for larger patches.
For example, for a patch with 449 nodes connected by 561 links it went down from 1460165ms to 1429ms.
> Optimize sortGraph

- CHANGELOG.md
- lerna.json
- packages/xod-arduino-deploy/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.24.0

- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/core/styles/components/PatchDocs.scss
> Do not wrap pin labels in Inspector and helpboxes

- CHANGELOG.md
- lerna.json
- packages/xod-client-electron/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.24.1

- CHANGELOG.md
- lerna.json
- packages/xod-client-electron/package.json
- packages/xod-client-electron/src/app/utils.js
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Merge 0.24.x back into master

- packages/xod-client-browser/test-func/pageObjects/Inspector.js
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
> Show normalized pin labels in Inspector pane

- packages/xod-client/src/project/components/layers/NodesLayer.jsx
- packages/xod-client/src/project/components/nodeParts/TerminalNodeBody.jsx
- packages/xod-client/src/project/selectors.js
- packages/xod-client/src/project/utils.js
> Show normalized labels in terminal nodes

- workspace/__lib__/xod/common-hardware/dhtxx-read-raw/patch.cpp
There were issues reported on our forum:
https://forum.xod.io/t/dht11-showing-correct-values-in-the-arduino-ide-but-0-values-in-xod/1096
https://forum.xod.io/t/problem-with-dht22-am2302-grove/536
https://forum.xod.io/t/temperature-sensor-am2302-dht22-not-working/980
This PR should solve most of them.
Now both kinds of sensors work fine with Arduino Mega and ESP8266-based boards.
> Make nodes for DHT11 and DHT2x more robust

- packages/xod-client-electron/src/app/arduinoCli.js
- packages/xod-client-electron/src/app/migrateArduinoPackages.js
> Migrate old installed packages into xod workspace

- CHANGELOG.md
- lerna.json
- packages/belt-holes/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-func-tools/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.25.0

- packages/xod-client/src/utils/menu.js
> Show ampersand in the menu item

- packages/xod-arduino/platform/runtime.cpp
- packages/xod-tabtest/cpp/Arduino.h
- workspace/__lib__/xod/common-hardware/servo/patch.cpp
- workspace/__lib__/xod/gpio/analog-read/patch.cpp
- workspace/__lib__/xod/gpio/digital-read/patch.cpp
- workspace/__lib__/xod/gpio/digital-write/patch.cpp
- workspace/__lib__/xod/gpio/pwm-write/patch.cpp
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/two-button-switch/__fixtures__/arduino.cpp
> Do not rely on NUM_DIGITAL_PINS being defined

- packages/arduino-cli/README.md
- packages/arduino-cli/src/config.js
- packages/arduino-cli/src/index.js
- packages/arduino-cli/src/optionParser.js
- packages/arduino-cli/test-func/index.spec.js
- packages/arduino-cli/test/fixtures/packages/esp8266/hardware/esp8266/2.4.2/boards.txt
- packages/arduino-cli/test/optionParser.spec.js
- packages/xod-arduino/platform/runtime.cpp
- packages/xod-client-electron/src/app/arduinoCli.js
- packages/xod-client-electron/src/app/main.js
- packages/xod-client-electron/src/app/migrateArduinoPackages.js
- packages/xod-client-electron/src/upload/messages.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/utils/menu.js
- packages/xod-tabtest/cpp/Arduino.h
- workspace/__lib__/xod/common-hardware/servo/patch.cpp
- workspace/__lib__/xod/gpio/analog-read/patch.cpp
- workspace/__lib__/xod/gpio/digital-read/patch.cpp
- workspace/__lib__/xod/gpio/digital-write/patch.cpp
- workspace/__lib__/xod/gpio/pwm-write/patch.cpp
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/two-button-switch/__fixtures__/arduino.cpp
Merges #1475, #1481, #1482, #1483, #1484
> Chore merge 0.25.x to master

- CHANGELOG.md
- lerna.json
- packages/arduino-cli/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.25.1

- workspace/__lib__/xod/core/buffer/patch.xodp
[generic-buffer-test.xodball.zip](https://github.com/xodio/xod/files/2502338/generic-buffer-test.xodball.zip)
> Make xod/core/buffer generic

- packages/xod-client/src/debugger/reducer.js
> Fix truncating of the compile & upload log

- packages/xod-project/src/Buses.re
- packages/xod-project/src/Patch.re
- packages/xod-project/src/Patch.rei
- packages/xod-project/src/index.js
- packages/xod-project/test/fixtures/jumperize.expected.xodball
- packages/xod-project/test/fixtures/jumperize.xodball
- packages/xod-project/test/fixtures/split-links-to-buses.expected.xodball
- packages/xod-project/test/fixtures/split-links-to-buses.xodball
Fixes #1414
Sorry about big fixture diffs 😬
> Create buses from links leading to variadic pins

- packages/xod-client/src/editor/components/NodeInspector.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/BoolPinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/DisabledInputWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/GenericPinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/NumberPinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PulsePinWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
> Add missing labels for variadic pins in Inspector

- CHANGELOG.md
- lerna.json
- packages/arduino-cli/package.json
- packages/xod-arduino/package.json
- packages/xod-cli/package.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-deploy/package.json
- packages/xod-fs/package.json
- packages/xod-patch-search/package.json
- packages/xod-pm/package.json
- packages/xod-project/package.json
- packages/xod-tabtest/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.25.2

- packages/xod-client/package.json
- yarn.lock
Had to make a fork, because https://github.com/rommguy/react-custom-scroll/pull/55 takes forever to get merged.
> Prevent sidebar scroll position jumps

- packages/xod-client/src/editor/messages.js
> Clarify message about bad references in paste

- .circleci/Dockerfile
- .circleci/config.yml
- packages/xod-client/package.json
- packages/xod-client/src/editor/messages.js
- workspace/__lib__/xod/common-hardware/sd-log/patch.cpp
- yarn.lock
Includes #1535, #1533, #1534, #1541
> Cherry pick hotfixes from master to 0.25.x

- .circleci/config.yml
- tools/install-arduinocli.ps1
It fixes bug with "bad content length" reported on the forum: https://forum.xod.io/t/problem-with-upload-to-arduino/1385/5
> Update arduino cli to 0.3.2

- .circleci/config.yml
- tools/install-arduinocli.ps1
From this PR: https://github.com/arduino/arduino-cli/pull/91
Because of https://github.com/arduino/arduino-cli/issues/87 (reproduced on Windows 10)
> Use fixed in PR arduino-cli version of 0.3.2

- packages/xod-client-browser/package.json
- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/package.json
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/package.json
- packages/xod-client/src/core/actions.js
- packages/xod-client/src/editor/components/LibSuggester.jsx
- packages/xod-client/src/editor/components/Suggester.jsx
- packages/xod-client/src/editor/containers/Editor.jsx
- packages/xod-client/src/utils/browser.js
- packages/xod-client/src/utils/constants.js
- yarn.lock
> Improve undo/redo hotkeys reliability

- CHANGELOG.md
* [ide] Fix certificate validation issue that messed up autoupdate on Windows (#1555)
* [ide] Update `arduino-cli` to 0.3.2 which fixes "Cannot update indexes" error that started occuring recently (#1560)
* [ide] Make undo/redo hotkeys more reliable (#1556)
* [ide] Fix "Select All" hotkey in Desktop IDE (#1554)
* [ide] Prevent scroll position jumps in sidebar (#1533)
* [nodes] Improve error handling in xod/common-hardware/sd-log (#1534)
> Update changelog for upcoming 0.25.3

- CHANGELOG.md
- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.25.3

- packages/xod-tabtest/src/TabData.re
- packages/xod-tabtest/test/TabData_jest.re
> Support comments in tabtests

- packages/xod-client-electron/src/view/containers/App.jsx
> Fix hanging upload process on error

- packages/xod-fs/src/unpack.js
> Do not save terminal patches for custom types

- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/user/selectors.js
- packages/xod-cloud-compile/src/compile.js
> Send Authorization header within cloud compilation request

- packages/xod-client/src/core/styles/components/Sidebar.scss
> Fix sidebar height in FF with CSS

- packages/xod-project/src/constants.js
- packages/xod-project/src/internal/patchPathUtils.js
- workspace/__lib__/xod/debug/console-log/patch.cpp
- workspace/__lib__/xod/debug/console-log/patch.xodp
- workspace/__lib__/xod/debug/project.xod
- workspace/__lib__/xod/debug/watch/patch.cpp
- workspace/__lib__/xod/debug/watch/patch.xodp
It closes #1625 
Changes in the docs: https://github.com/xodio/xod-docs/pull/109
> Move debug nodes into new library

- packages/xod-client/src/editor/components/SidebarSwitches.jsx
> Add tooltips for show/hide sidebar pane buttons

- packages/xod-client/src/core/styles/components/Node.scss
- packages/xod-client/src/project/components/Node.jsx
- packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx
- packages/xod-project/src/internal/patchPathUtils.js
- packages/xod-project/src/patchPathUtils.js
> Make a fancy look for `xod/patch-nodes/jumper`

- packages/xod-client-electron/src/app/utils.js
- packages/xod-client-electron/webpack.config.js
> Fix including of bundled Arduino libraries in dev mode

- workspace/__lib__/xod/debug/tweak-string-16/patch.cpp
> Fix tweak-string-16 implementation

- packages/xod-client/src/core/styles/components/Node.scss
- packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx
> Fix crash of two linked jumper nodes

- packages/belt-holes/bsconfig.json
- packages/xod-arduino/bsconfig.json
- packages/xod-func-tools/bsconfig.json
- packages/xod-project/bsconfig.json
- packages/xod-tabtest/bsconfig.json
- packages/xod-tabtest/src/TabData.re
There is no issue. Introduced by me in the #1682
> Get rid of the warning in xod-tabtest

- workspace/__lib__/xod/core/clock/patch.cpp
- workspace/__lib__/xod/core/clock/patch.test.tsv
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
> make `clock` behave like `continuously` when IVAL is set to 0

- packages/xod-client/src/hinting/patchMarkers.js
- packages/xod-client/src/hinting/typeDeduction.js
> Tweak list of actions that trigger hinting update

- packages/xod-client/src/editor/utils.js
- packages/xod-client/src/project/nodeLayout.js
> Fix calculating of entities bounding box

- packages/xod-client/src/project/nodeLayout.js
> Make pixel perfect links

- packages/xod-client/src/core/styles/components/Breadcrumbs.scss
- packages/xod-client/src/core/styles/components/Tabs.scss
> Fix tabs height when code editor is open

- CHANGELOG.md
- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/sharp-irm/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/color/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/debug/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.28.1

- CHANGELOG.md
- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- packages/xod-client/src/core/styles/abstracts/variables.scss
- packages/xod-client/src/core/styles/components/Breadcrumbs.scss
- packages/xod-client/src/core/styles/components/Tabs.scss
- packages/xod-client/src/editor/containers/Patch/modes/linking.jsx
- packages/xod-client/src/project/reducer.js
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/sharp-irm/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/color/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/debug/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
Merges #1716, #1717, #1719, #1722
> Merge 0.28.x into master

- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
There is no issue. But this bug was reported on the forum: https://forum.xod.io/t/cannot-properly-install/2050
> Fix default board index value

- tools/generate-tutorial-docs.js
> Tweak tutorial generator tool to make correct index of exercises

- CHANGELOG.md
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/servo/project.xod
- workspace/__lib__/xod-dev/sharp-irm/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/color/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/debug/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/mutex/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.29.1

- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
(For real this time! The previous one didn't happen because all the changes were in stdlib and lerna did't bump package versions)
> Release 0.29.1 

- packages/xod-client/src/projectBrowser/components/PatchGroup.jsx
The bug was introduced by me in the PR #1752
> Fix PropType in PatchGroup component

- workspace/__lib__/xod/core/if-else(byte)/patch.xodp
- workspace/__lib__/xod/core/if-else(number)/patch.xodp
- workspace/__lib__/xod/core/if-else(string)/patch.xodp
- workspace/__lib__/xod/core/if-else/patch.cpp
- workspace/__lib__/xod/core/if-else/patch.xodp
- workspace/test/test-core/test-generc-if-else-with-booleans/patch.test.tsv
- workspace/test/test-core/test-generc-if-else-with-booleans/patch.xodp
- workspace/test/test-core/test-generc-if-else-with-bytes/patch.test.tsv
- workspace/test/test-core/test-generc-if-else-with-bytes/patch.xodp
- workspace/test/test-core/test-generc-if-else-with-numbers/patch.test.tsv
- workspace/test/test-core/test-generc-if-else-with-numbers/patch.xodp
- workspace/test/test-core/test-generc-if-else-with-strings/patch.test.tsv
- workspace/test/test-core/test-generc-if-else-with-strings/patch.xodp
> Make `xod/core/if-else` truly generic

- workspace/__lib__/xod-dev/esp8266-mcu/is-connected/patch.cpp
- workspace/__lib__/xod-dev/esp8266-mcu/is-connected/patch.xodp
A successor of #1514
The node looks like this:
> Add `xod-dev/esp8266-mcu/is-connected`

- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/editor/actions.js
- packages/xod-client/src/user/actions.js
It closes #1779 and closes #1780
> Fix showing cloud compilation limits

- packages/xod-client-electron/src/app/workspaceActions.js
> Fix workspace creation and show a bundled project on opening not a XOD file

- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
> Show broken patches even if it should be hidden by filter

- workspace/welcome-again/main/patch.xodp
> Add promo-link from welcome-again banner

- packages/arduino-cli/src/optionParser.js
- packages/arduino-cli/test-func/index.spec.js
- packages/arduino-cli/test/fixtures/packages/fictional/hardware/fake/1.2.3/boards.txt
- packages/arduino-cli/test/optionParser.spec.js
- packages/xod-client-electron/src/app/arduinoActions.js
- packages/xod-client-electron/src/app/main.js
- packages/xod-client-electron/src/debugger/ipcActions.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-deploy/src/serialport.js
This fixes problems with debugging Arduino Leonardo and some other boards.
> Respect serial.disableRTS option from boards.txt when opening serialport for debugging

- packages/xod-client/src/user/actions.js
> Fix library publishing

- CHANGELOG.md
- lerna.json
- packages/xod-client-browser/package.json
- packages/xod-client-electron/package.json
- packages/xod-client/package.json
- workspace/__lib__/xod-dev/ds-rtc/project.xod
- workspace/__lib__/xod-dev/esp8266-mcu/project.xod
- workspace/__lib__/xod-dev/esp8266/project.xod
- workspace/__lib__/xod-dev/pn532-nfc/project.xod
- workspace/__lib__/xod-dev/servo/project.xod
- workspace/__lib__/xod-dev/sharp-irm/project.xod
- workspace/__lib__/xod-dev/w5500/project.xod
- workspace/__lib__/xod/bits/project.xod
- workspace/__lib__/xod/color/project.xod
- workspace/__lib__/xod/common-hardware/project.xod
- workspace/__lib__/xod/core/project.xod
- workspace/__lib__/xod/datetime/project.xod
- workspace/__lib__/xod/debug/project.xod
- workspace/__lib__/xod/gpio/project.xod
- workspace/__lib__/xod/i2c/project.xod
- workspace/__lib__/xod/math/project.xod
- workspace/__lib__/xod/mutex/project.xod
- workspace/__lib__/xod/net/project.xod
- workspace/__lib__/xod/stream/project.xod
- workspace/__lib__/xod/uart/project.xod
- workspace/__lib__/xod/units/project.xod
> Release 0.30.1

- packages/xod-tabtest/cpp/Makefile
- workspace/test/test-core/test-error-propagation-through-defer-nodes/patch.test.tsv
- workspace/test/test-core/test-error-propagation-through-defer-nodes/patch.xodp
Failing tests were ignored because of the loop.
> Fix tabtests runner exit code

- workspace/__lib__/xod-dev/servo/servo/patch.xodp
- workspace/__lib__/xod/common-hardware/h-bridge-dc-motor/patch.xodp
- workspace/__lib__/xod/common-hardware/led/patch.xodp
This closes partially #1794.
The rest of the issue is about documentation.
> Replace UPDs with ACTs on idempotent actuators

- workspace/__lib__/xod/common-hardware/button/patch.xodp
- workspace/__lib__/xod/gpio/digital-read-pullup/patch.cpp
- workspace/__lib__/xod/gpio/digital-read-pullup/patch.xodp
> Add digital-read with pull-up

- workspace/__lib__/xod/common-hardware/binary-sensor/patch.xodp
- workspace/__lib__/xod/common-hardware/button/patch.xodp
- workspace/__lib__/xod/common-hardware/mechanical-switch/patch.xodp
- workspace/__lib__/xod/common-hardware/pwm-load/patch.xodp
- workspace/__lib__/xod/common-hardware/relay/patch.xodp
> Augment common hardware standard library

- packages/xod-patch-search/test/index.spec.js
- workspace/__lib__/xod-dev/hc-sr04/example-advanced/patch.xodp
- workspace/__lib__/xod-dev/hc-sr04/example-quick-start/patch.xodp
- workspace/__lib__/xod-dev/hc-sr04/hc-sr04-device/patch.cpp
- workspace/__lib__/xod-dev/hc-sr04/hc-sr04-device/patch.xodp
- workspace/__lib__/xod-dev/hc-sr04/hc-sr04-range-meter/patch.xodp
- workspace/__lib__/xod-dev/hc-sr04/ping/patch.cpp
- workspace/__lib__/xod-dev/hc-sr04/ping/patch.xodp
- workspace/__lib__/xod-dev/hc-sr04/project.xod
- workspace/__lib__/xod/common-hardware/hc-sr04-ultrasonic-range/patch.xodp
- workspace/__lib__/xod/common-hardware/hc-sr04-ultrasonic-time/patch.xodp
- workspace/__lib__/xod/units/standard-sound-speed/patch.xodp
With this PR https://github.com/xodio/xod-docs/pull/141 it will close #1792
> Extract hc-sr04 into separate library

- packages/xod-arduino/platform/program.tpl.cpp
- packages/xod-arduino/src/templates.js
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/two-button-switch/__fixtures__/arduino.cpp
> Fix tweak nodes behaviour bug 

- workspace/__lib__/xod-dev/dht/dht11-device/patch.cpp
- workspace/__lib__/xod-dev/dht/dht11-device/patch.xodp
- workspace/__lib__/xod-dev/dht/dht11-hygrometer/patch.xodp
- workspace/__lib__/xod-dev/dht/dht2x-device/patch.cpp
- workspace/__lib__/xod-dev/dht/dht2x-device/patch.xodp
- workspace/__lib__/xod-dev/dht/dht2x-hygrometer/patch.xodp
- workspace/__lib__/xod-dev/dht/dht2x-pack/patch.xodp
- workspace/__lib__/xod-dev/dht/dhtxx-read-raw/patch.cpp
- workspace/__lib__/xod-dev/dht/dhtxx-read-raw/patch.xodp
- workspace/__lib__/xod-dev/dht/example-dht11/patch.xodp
- workspace/__lib__/xod-dev/dht/project.xod
- workspace/__lib__/xod-dev/dht/read(dht11-device)/patch.xodp
- workspace/__lib__/xod-dev/dht/read(dht2x-device)/patch.xodp
- workspace/__lib__/xod-dev/dht/read/patch.xodp
- workspace/__lib__/xod-dev/dht/unpack-dht11-device/patch.cpp
- workspace/__lib__/xod-dev/dht/unpack-dht11-device/patch.xodp
- workspace/__lib__/xod-dev/dht/unpack-dht2x-device/patch.cpp
- workspace/__lib__/xod-dev/dht/unpack-dht2x-device/patch.xodp
- workspace/__lib__/xod/common-hardware/dht11-thermometer/patch.xodp
- workspace/__lib__/xod/common-hardware/dht2x-pack/patch.xodp
- workspace/__lib__/xod/common-hardware/dht2x-thermometer/patch.xodp
- workspace/__lib__/xod/common-hardware/dhtxx-read-raw/patch.xodp
- workspace/__lib__/xod/core/throttle/patch.cpp
- workspace/test/test-core/test-throttle-numbers/patch.test.tsv
- workspace/test/test-core/test-throttle-time/patch.test.tsv
It closes #1791 (without one point about docs, but this one I'll close soon with the other hardware nodes)
> Extract DHT nodes

- packages/xod-project/src/constants.js
- workspace/__lib__/xod/core/cast-to-string(port)/patch.cpp
- workspace/__lib__/xod/core/cast-to-string(port)/patch.xodp
> Make port type castable to string type

- packages/xod-client/src/editor/codemirrorXodMode.js
> Highlight a few more core functions in C++ editor

- packages/xod-client-electron/src/arduinoDependencies/components/UpdateArduinoPackagesPopup.jsx
- packages/xod-client-electron/src/arduinoDependencies/runners.js
- packages/xod-client-electron/src/upload/arduinoCli.js
- packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
- workspace/__packages__/package_index.json
There is no issue, but there is the report on the forum: https://forum.xod.io/t/i-need-help-for-the-lcd-i2c-tutorial/2645/
> Fix updating of package indexes and bundle the last one

- workspace/__lib__/xod-dev/dht/dhtxx-read-raw/patch.cpp
- workspace/__lib__/xod-dev/dht/read(dht2x-device)/patch.xodp
- workspace/__lib__/xod-dev/dht/unpack-dht2x-device/patch.xodp
> Fix dht library

- packages/xod-arduino/platform/patchContext.tpl.cpp
- packages/xod-arduino/platform/program.tpl.cpp
- packages/xod-arduino/platform/runtime.cpp
- workspace/__lib__/xod/core/defer(boolean)/patch.cpp
- workspace/__lib__/xod/core/defer(byte)/patch.cpp
- workspace/__lib__/xod/core/defer(number)/patch.cpp
- workspace/__lib__/xod/core/defer(pulse)/patch.cpp
- workspace/__lib__/xod/core/defer(string)/patch.cpp
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/test/test-core/test-feedback-loops/patch.test.tsv
- workspace/test/test-core/test-feedback-loops/patch.xodp
- workspace/two-button-switch/__fixtures__/arduino.cpp
Covers a few edge-cases such as a `defer` node surrounded by closed `gate`s
> Improve error propagation through defer nodes

- workspace/__lib__/xod/common-hardware/button/patch.xodp
> Fix debounce in the button node

- packages/xod-arduino/platform/configuration.tpl.cpp
- packages/xod-arduino/src/Transpiler.re
- packages/xod-arduino/src/Transpiler.rei
- packages/xod-arduino/src/constants.js
- packages/xod-arduino/src/templates.js
- packages/xod-arduino/src/transpiler.js
- packages/xod-arduino/src/types.js
- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-cli/src/listrTasks.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/editor/components/inspectorWidgets/index.js
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
- packages/xod-client/src/user/messages.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/utils.js
- packages/xod-tabtest/src/Tabtest.re
> Add =XOD_USERNAME literal

- packages/xod-client-electron/src/view/formatError.js
> Show error message about missing value for global literal preperly

- packages/xod-arduino/src/index.js
- packages/xod-arduino/src/messages.js
- packages/xod-arduino/src/transpiler.js
- packages/xod-arduino/test/transpiler.spec.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/project/actions.js
- packages/xod-client/src/project/messages.js
- packages/xod-client/src/user/actions.js
- packages/xod-client/src/user/messages.js
- packages/xod-client/src/utils/urls.js
- packages/xod-func-tools/src/promises.js
- packages/xod-project/src/constants.js
> Implement `XOD_TOKEN` literal and make possible to use async value getters for globals

- packages/xod-client-electron/src/app/workspaceActions.js
- packages/xod-client-electron/src/shared/messages.js
- packages/xod-client-electron/src/view/actions.js
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/index.js
- packages/xod-client/src/project/actions.js
- packages/xod-client/src/project/reducer.js
- packages/xod-client/src/utils/deriveProjectName.js
- packages/xod-client/test/deriveProjectName.spec.js
> Derive project name from filename

- packages/xod-client/src/editor/components/LibSuggester.jsx
- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
- packages/xod-client/stories/LibSuggester.jsx
- packages/xod-client/stories/Suggester.jsx
- packages/xod-pm/src/fetch.js
- packages/xod-pm/src/index.js
- packages/xod-pm/src/utils.js
- packages/xod-pm/test-func/fetch.spec.js
- packages/xod-pm/test/utils.spec.js
Now it is possible to search for libraries within XOD IDE in the "Add Library" suggester.
Plus
+ fixed Suggester storybook
+ added LibSuggester to storybook
+ little refactoring
> Add search for libraries within XOD IDE

- packages/arduino-cli/package.json
- packages/arduino-cli/src/index.js
- yarn.lock
> Fix arduino-cli and spaces in username on Windows

- CHANGELOG.md
It's a part of releasing pipeline.
> Prepare changelog for 0.32.0

- workspace/__lib__/xod-cloud/feeds/cloud-store-custom/patch.xodp
- workspace/__lib__/xod-cloud/feeds/cloud-store/patch.xodp
- workspace/__lib__/xod-cloud/feeds/is-non-200-response/patch.xodp
- workspace/__lib__/xod-cloud/feeds/project.xod
> Implement xod-cloud publish nodes

- packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js
- packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
The bug was reported on [our forum](https://forum.xod.io/t/bug-in-latest-version-of-xod/3011)
> Fix crash on sendidng tweak pulses

- CHANGELOG.md
* [ide] Fix crash on sending tweak pulses (#1914)
* [core] Fix implementation of placement new operator for cores that do not provide their own (#1915)
* [xod/core/equal(boolean)](https://xod.io/libs/xod/core/equal(boolean\)/) (#1916)
> Prepare changelog for 0.32.1

- packages/xod-client/src/editor/stopSimulationMiddleware.js
> Stop simulation on creating/opening project

- packages/xod-arduino/tools/test-avr-size.sh
- tools/update-transpiled-fixtures.sh
- workspace/big-patch/__fixtures__/arduino.cpp
- workspace/big-patch/alarm-sound/patch.xodp
- workspace/big-patch/main/patch.xodp
- workspace/big-patch/max-value/patch.xodp
- workspace/big-patch/panic/patch.xodp
- workspace/big-patch/play-note/patch.cpp
- workspace/big-patch/play-note/patch.xodp
- workspace/big-patch/project.xod
- workspace/big-patch/show-info/patch.xodp
For more realistic analysis of generated file sizes when developing new features
> Add “big patch” fixture

- packages/xod-arduino/platform/types.h
- workspace/__lib__/xod/color/color/patch.cpp
- workspace/big-patch/__fixtures__/arduino.cpp
- workspace/blink/__fixtures__/arduino.cpp
- workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
- workspace/lcd-time/__fixtures__/arduino.cpp
- workspace/two-button-switch/__fixtures__/arduino.cpp
> Add the XColor type structure

- workspace/__ardulib__/README.md
- workspace/__ardulib__/WS2812_NoBufffer/WS2812.cpp
- workspace/__ardulib__/WS2812_NoBufffer/WS2812.h
- workspace/__ardulib__/WS2812_NoBufffer/esp8266.c
- workspace/__lib__/xod-dev/ws2812/clear/patch.cpp
- workspace/__lib__/xod-dev/ws2812/clear/patch.xodp
- workspace/__lib__/xod-dev/ws2812/example-advanced/patch.xodp
- workspace/__lib__/xod-dev/ws2812/example-quickstart/patch.xodp
- workspace/__lib__/xod-dev/ws2812/fill-solid/patch.cpp
- workspace/__lib__/xod-dev/ws2812/fill-solid/patch.xodp
- workspace/__lib__/xod-dev/ws2812/project.xod
- workspace/__lib__/xod-dev/ws2812/ws2812-device/patch.cpp
- workspace/__lib__/xod-dev/ws2812/ws2812-device/patch.xodp
- workspace/__lib__/xod-dev/ws2812/ws2812-mono/patch.xodp
- workspace/__lib__/xod/color/color/patch.cpp
- workspace/__lib__/xod/color/pulse-on-change(color)/patch.cpp
- workspace/__lib__/xod/color/pulse-on-change(color)/patch.xodp
It closes #1921 
Also, it contains a little fix related to #1922 (PR #1926)
> Implement xod-dev/ws2812

- workspace/__lib__/xod/core/pulse-on-change(byte)/patch.cpp
- workspace/__lib__/xod/core/pulse-on-change(byte)/patch.test.tsv
- workspace/__lib__/xod/core/pulse-on-change(byte)/patch.xodp
added pulse-on-change (byte) to generic type
close [#1938](https://github.com/xodio/xod/issues/1938)
> added pulse-on-change(byte)

- workspace/__ardulib__/Graphics/Circle.h
- workspace/__ardulib__/Graphics/Circle.inl
- workspace/__lib__/xod/graphics/circle-outline-colored/patch.cpp
- workspace/__lib__/xod/graphics/circle-outline-colored/patch.xodp
- workspace/__lib__/xod/graphics/circle-outline/patch.cpp
- workspace/__lib__/xod/graphics/circle-outline/patch.xodp
- workspace/__lib__/xod/graphics/circle-solid-colored/patch.cpp
- workspace/__lib__/xod/graphics/circle-solid-colored/patch.xodp
- workspace/__lib__/xod/graphics/circle-solid/patch.cpp
- workspace/__lib__/xod/graphics/circle-solid/patch.xodp
Add the `Circle` class to the `__ardulib__/Graphics/` and `xod/graphics` library.
> Add the Circle graphic primitive to the Graphic library.

- packages/xod-arduino/platform/program.tpl.cpp
- packages/xod-arduino/src/formatTweakMessage.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/custom-types.js
- packages/xod-project/src/flatten.js
- packages/xod-project/src/internal/pinTypes.js
- packages/xod-project/src/patchPathUtils.js
- packages/xod-project/src/utils.js
- packages/xod-project/test/customTypeLiterals.spec.js
- packages/xod-project/test/flatten.spec.js
- packages/xod-project/test/patchPathUtils.spec.js
- workspace/__ardulib__/WS2812_NoBufffer/WS2812.inl
- workspace/__lib__/xod-dev/ws2812/ws2812-mono/patch.xodp
- workspace/__lib__/xod-dev/ws2812/ws2812-pattern/patch.xodp
- workspace/__lib__/xod/debug/tweak-color/patch.cpp
- workspace/__lib__/xod/debug/tweak-color/patch.xodp
> Support color type debugging features

- workspace/__ardulib__/Graphics/Rectangle.h
- workspace/__ardulib__/Graphics/Rectangle.inl
- workspace/__ardulib__/Graphics/XGraphics.h
- workspace/__lib__/xod/graphics/rect-outline-colored/patch.cpp
- workspace/__lib__/xod/graphics/rect-outline-colored/patch.xodp
- workspace/__lib__/xod/graphics/rect-outline/patch.cpp
- workspace/__lib__/xod/graphics/rect-outline/patch.xodp
- workspace/__lib__/xod/graphics/rect-solid-colored/patch.cpp
- workspace/__lib__/xod/graphics/rect-solid-colored/patch.xodp
- workspace/__lib__/xod/graphics/rect-solid/patch.cpp
- workspace/__lib__/xod/graphics/rect-solid/patch.xodp
- Add the `Rectangle` class to the `__ardulib__/Graphics/` and `xod/graphics` library.
- Fix the unterminated `#ifndef` at the `XGraphics.h`
> Add the Rectangle graphic primitive to the Graphic library.

- workspace/__ardulib__/README.md
- workspace/__ardulib__/ST7735/XST7735.cpp
- workspace/__ardulib__/ST7735/XST7735.h
- workspace/__lib__/xod-dev/st7735-display/init-b/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/init-b/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/init-g/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/init-g/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/init-rg/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/init-rg/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/init-rr/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/init-rr/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/project.xod
- workspace/__lib__/xod-dev/st7735-display/render/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/render/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-b-device/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-b/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-g-device/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-g/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rg-device/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rg/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rr-device/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rr/patch.xodp
- workspace/__lib__/xod-dev/st7735-display/st7735/patch.cpp
- workspace/__lib__/xod-dev/st7735-display/st7735/patch.xodp
Add custom c++ library and `xod-dev/st7735-display` library.
> Support of ST7735 based TFT displays 

- packages/xod-arduino/src/transpiler.js
- packages/xod-project/src/Buses.re
- packages/xod-project/src/Buses.rei
- packages/xod-project/src/Buses_Js.re
- packages/xod-project/src/Pin.re
- packages/xod-project/src/Pin.rei
- packages/xod-project/src/TypeDeduction.re
- packages/xod-project/src/index.js
- packages/xod-project/test/buses.spec.js
- packages/xod-project/test/fixtures/jumperize.expected.xodball
- packages/xod-project/test/fixtures/linkify.expected.xodball
- packages/xod-project/test/fixtures/linkify.xodball
- workspace/test/test-core/test-feedback-loops/patch.xodp
> Stop relying on jumpers when connecting buses or deducing types

- tools/publish-stdlib.sh
To automate [this part](https://github.com/xodio/xod/wiki/Releasing-a-New-Version#update-xod-libraries) of the release process.
> Add tool for publishing stdlib

- workspace/__ardulib__/Graphics/Triangle.h
- workspace/__ardulib__/Graphics/Triangle.inl
- workspace/__lib__/xod/graphics/triangle-outline-colored/patch.cpp
- workspace/__lib__/xod/graphics/triangle-outline-colored/patch.xodp
- workspace/__lib__/xod/graphics/triangle-outline/patch.cpp
- workspace/__lib__/xod/graphics/triangle-outline/patch.xodp
- workspace/__lib__/xod/graphics/triangle-solid-colored/patch.cpp
- workspace/__lib__/xod/graphics/triangle-solid-colored/patch.xodp
- workspace/__lib__/xod/graphics/triangle-solid/patch.cpp
- workspace/__lib__/xod/graphics/triangle-solid/patch.xodp
Add the Triangle class to the `__ardulib__/Graphics/` and `xod/graphics` library.
> Add the Triangle graphic primitive to the Graphic library.

- workspace/__lib__/xod/core/cast-to-pulse(boolean)/patch.xodp
- workspace/__lib__/xod/core/pulse-on-false/patch.test.tsv
- workspace/__lib__/xod/core/pulse-on-false/patch.xodp
- workspace/__lib__/xod/core/pulse-on-true/patch.test.tsv
- workspace/__lib__/xod/core/pulse-on-true/patch.xodp
> Make pulse-on-* consistent and not trigger on start

- packages/xod-project/src/internal/patchPathUtils.js
- packages/xod-project/src/patchPathUtils.js
- packages/xod-project/src/project.js
- packages/xod-project/test/project.spec.js
There is no issue. It was an unhandled case in my previous PR https://github.com/xodio/xod/pull/1999, now it fixed
> Fixed cloning of specialization patches

- packages/xod-client/src/core/assets/index.html
- packages/xod-client/src/core/styles/components/Editor.scss
- packages/xod-client/src/core/styles/components/Inspector.scss
- packages/xod-client/src/core/styles/components/PointingPopup.scss
- packages/xod-client/src/core/styles/components/ProjectBrowser.scss
- packages/xod-client/src/editor/components/inspectorWidgets/ColorPickerWidget.jsx
- packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/ColorPinWidget.jsx
> Merge 0.33.x into master

- packages/arduino-cli/src/index.js
> Support arduino-cli v0.11.0

- packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
- packages/xod-client/src/project/components/Node.jsx
- packages/xod-project/src/index.js
- packages/xod-project/src/patch.js
> Make color-type outputs bindable

- .circleci/config.yml
- packages/arduino-cli/src/index.js
- packages/xod-cli/test-func/compile-upload.spec.js
- packages/xod-client-electron/src/app/main.js
- packages/xod-deploy-bin/src/messages.js
- tools/install-arduinocli.ps1
Tested manually. Works fine on macOS.
Building prerelease on this branch and will test on other OS. Please, wait until I remove the WIP label ;)
> Update bundled arduino-cli to 0.12.0

- CHANGELOG.md
* [nodes] Ensure compatibility `xod-dev/servo` and `xod/gpio` with ESP32 boards (#2038)
* [ide] Make possible to send char literals to `tweak-byte`s in live session (#2041)
* [c++] Optimise memory consumption of `tweak-string` nodes (#2042)
* [ide] Fix loading of a newly added package index file in extra.txt (#2038)
* [ide] Fix hotkeys in Inspector Pin widgets (#2040)
* [nodes] Fix `tweak-string` nodes (#2042)
> Prepare changelog for upcoming 0.35.2

- CHANGELOG.md
* [core] Introduce records — an easy way to pack multiple data fields into a custom type and to serialize it to JSON. Check out [the guide article](https://xod.io/docs/guide/records/) for details (#2051)
* [c++] Introduce [`setImmediate`](https://xod.io/docs/reference/node-cpp-api/#setImmediate) API, that greatly optimises cases that require sheduling evaluation right after the current transaction completes (#2056)
* [ide] Add information about constant types in C++ cheatsheet in the sidebar (#2045)
* [nodes] Make xod graphics bitmaps compile on non-avr boards (#2053)
* [nodes] Fix `xod-dev/esp8266-mcu/lan-ip` implementation (#2050)
* Add `to-json` abstract node and specialisations for primitive data types to [xod/json](https://xod.io/libs/xod/json) library (#2051)
> Update changelog for the upcoming v0.36.0

- workspace/__lib__/xod/core/animation-unit/patch.cpp
- workspace/__lib__/xod/debug/is-receiving/patch.cpp
> Fix `xod/core/animation-unit` and `xod/debug/is-receiving`

- workspace/welcome-to-xod/001-hello/patch.xodp
> Fix typo in welcome-to-xod

- packages/xod-client-browser/src/containers/App.jsx
- packages/xod-client-electron/src/view/containers/App.jsx
- packages/xod-client/src/core/containers/App.jsx
- packages/xod-client/src/projectBrowser/components/ProjectBrowserPopups.jsx
- packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
> Show create new patch popup even when the project browser is hidden

- packages/xod-client/src/core/styles/components/Debugger.scss
- packages/xod-client/src/debugger/containers/Debugger.jsx
- packages/xod-client/src/debugger/messages.js
> Copy and save logs from deployment pane

- package.json
- packages/xod-client-browser/test-func/copy-save.spec.js
- packages/xod-client-browser/test-func/pageObjects/Debugger.js
- packages/xod-client-browser/test-func/pageObjects/Input.js
- packages/xod-client-browser/test-func/pageObjects/Inspector.js
- packages/xod-client/src/debugger/containers/Debugger.jsx
- yarn.lock
It relates to #2076 and my previous PR #2078
> Add tests for copy and save log feature

- packages/xod-client/src/core/containers/App.jsx
> Prevent toggling helpbox by "h" key when input focused

- packages/xod-client-browser/test-func/utils/getPage.js
- packages/xod-project/src/constants.js
- packages/xod-project/src/custom-types.js
- workspace/__lib__/xod/core/cast-to-string(micros)/patch.cpp
- workspace/__lib__/xod/core/cast-to-string(micros)/patch.xodp
- workspace/__lib__/xod/core/delta-micros/patch.cpp
- workspace/__lib__/xod/core/delta-micros/patch.xodp
- workspace/__lib__/xod/core/micros/patch.cpp
- workspace/__lib__/xod/core/micros/patch.xodp
- workspace/__lib__/xod/core/to-seconds/patch.cpp
- workspace/__lib__/xod/core/to-seconds/patch.xodp
- workspace/__lib__/xod/gpio/change-interrupt/patch.cpp
- workspace/__lib__/xod/gpio/change-interrupt/patch.xodp
- workspace/__lib__/xod/gpio/fall-interrupt/patch.cpp
- workspace/__lib__/xod/gpio/fall-interrupt/patch.xodp
- workspace/__lib__/xod/gpio/low-interrupt/patch.cpp
- workspace/__lib__/xod/gpio/low-interrupt/patch.xodp
- workspace/__lib__/xod/gpio/rise-interrupt/patch.cpp
- workspace/__lib__/xod/gpio/rise-interrupt/patch.xodp
> Add interrupt nodes and `micros` type with some utility nodes in the standard library
