xodio/xod

.travis.yml, README.md, package.json, packages/xod-arduino/.gitignore, packages/xod-arduino/package.json, packages/xod-arduino/platform/patchContext.tpl.cpp, packages/xod-arduino/platform/preamble.h, packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/platform/runtime.cpp, packages/xod-arduino/src/templates.js, packages/xod-arduino/test/fixtures/implList.cpp, packages/xod-arduino/test/fixtures/program.cpp, packages/xod-arduino/tools/test-avr-size.sh, packages/xod-arduino/tools/test-cpp.sh, packages/xod-arduino/yarn.lock, packages/xod-client-electron/test-func/fixtures/blink.cpp, packages/xod-fs/yarn.lock, workspace/blink/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/lib/xod/core/constant-boolean/any.cpp, workspace/lib/xod/core/constant-number/any.cpp, workspace/lib/xod/core/constant-string/any.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
Closes #732 
RAM consumption lowered 2× to 3×.
Also, C++ testing is now incorporated in Travis CI. The `.travis.yml` is slightly evolved to get better caching and log reporting.
I’ve tested `*fixtures*/*.cpp` on real hardware. Found no regressions.
=> Move static data to the PGM space on AVR MCU’s

workspace/lib/xod/core/count/any.cpp
=> Allow fractional steps in `count` node

packages/xod-client/src/core/selectors.js
Closes #763
Very silly mistake introduced in #751 🙈
=> fix(xod-client): switch from getPatchByPathUnsafe to safe version in getPatchForHelpbar selector

packages/xod-arduino/platform/runtime.cpp, packages/xod-client-electron/test-func/fixtures/blink.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
Fixes #747 
Now the fixture project `lcd-time` should compile on every platform we show in the upload dialog drop down.
=> Provide C dtostrf function for all platforms

packages/xod-arduino/platform/runtime.cpp, packages/xod-arduino/tools/test-avr-size.sh, packages/xod-client-electron/test-func/fixtures/blink.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/lib/xod/common-hardware/button/patch.xodp, workspace/lib/xod/core/buffer/any.cpp, workspace/lib/xod/core/count/any.cpp, workspace/lib/xod/core/debounce-boolean/any.cpp, workspace/lib/xod/core/fade/any.cpp, workspace/lib/xod/core/flip-flop/any.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
Fixes #737 
Also in this PR:
- Implement `isTimedOut`, freeze `transactionTime` value for the whole transaction span as stated in docs
- Fix false firing of `xod/common-hardware/button` on start
It was expected that RAM consumption will be lower after switching from own state to output storage. And it is. However, the size test fixture is a simple blink. It had 1 byte (bool) of own storage saved (the memory of flip-flop). On the other side, extra 4 bytes were consumed by `g_transactionTime`. Thus the final firmware size increased a bit on this particular singular case.
=> Access outputs directly in C++ runtime

workspace/lib/xod/common-hardware/adxl335-accelerometer/patch.xodp, workspace/lib/xod/common-hardware/adxl335-convert/patch.xodp
The PR complements the new IMU node set with a driver for ADXL335 which is one of the most popular accelerometers.
=> Implement adxl335-accelerometer node

packages/xod-client/src/core/styles/components/PatchGroupItem.scss
=> Make background for selected project browser item’s buttons non-transparent

packages/xod-client/src/editor/selectors.js
Fixes an error when closing last editor tab
=> Return reasonable value from getCurrentPatchOffset when no tabs are open

packages/xod-client/src/projectBrowser/reducer.js, packages/xod-client/src/projectBrowser/selectors.js
A couple of small project browser tweaks:
- sort local patches alphabetically
- keep selection after renaming patch
=> Sort local patches alphabetically

CHANGELOG.md
Pretty-printed copy below:
* Brand new tutorial. It has two versions: the first one is embedded right into the `welcome-to-xod` project you see after the desktop IDE installation or browser-based IDE launch; the second one is published statically in the  [documentation](https://xod.io/docs/) section of the site.
* The debugger and watches! Now, you can watch for value changes in real-time right inside the desktop XOD IDE. Place a `xod/core/watch` node, link it, and upload the program with “Debug after upload” checkbox set. The debugger also lets you view incoming serial data log like the Serial Monitor in Arduino IDE does.
* Bulk selection and mass actions. Hold the Ctrl key (Command on macOS) while clicking on nodes, links, or comments to select multiple entities. After that, you could …
=> Update the changelog for the upcoming v0.14.0

docs/README.md, docs/guide/README.md, docs/guide/shortcuts/README.md, packages/xod-client-browser/src/containers/App.jsx, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/utils/menu.js
Ad-hoc PR sourced from a [forum thread](https://forum.xod.io/t/is-there-ui-documentation/109/7).
I intentionally left out some shortcuts because their future does not look clear. E.g. `Ctrl+R` to rename: does this operation ever deserve a shortcut or at least such “tasty” keystroke?! This is yet to be discussed. For now, only stable and vital combinations are included.
Also note that in case of the PR approval, #796 and #811 should have changes in docs as well.
=> Document mouse and keyboard shortcuts

packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/utils/constants.js, packages/xod-client/src/utils/menu.js
Because we could not select all text in an input before :(
=> Add ‘Select All’ command to desktop IDE

.travis.yml, appveyor.yml, tools/verify-git-clean.sh
…so that we don’t forget to bump `yarn.lock` and keep `.gitignore` DX friendly.
=> Chore: verify Git repo is kept clean during CI

packages/xod-client/src/core/styles/components/App.scss, packages/xod-client/src/core/styles/components/Debugger.scss, packages/xod-client/src/core/styles/components/Editor.scss, packages/xod-client/src/core/styles/components/Inspector.scss, packages/xod-client/src/core/styles/components/PatchWrapper.scss, packages/xod-client/src/core/styles/components/Sidebar.scss, packages/xod-client/src/core/styles/components/Suggester.scss, packages/xod-client/src/core/styles/components/Workarea.scss, packages/xod-client/src/core/styles/main.scss, packages/xod-client/src/editor/components/Inspector.jsx, packages/xod-client/src/editor/containers/Editor.jsx, packages/xod-client/src/editor/containers/Patch/index.jsx
It will close #819.
Also, I do a little refactoring of CSS-styles for some nearest DOM-elements.
I think that we could use a flex-box for a debugger & helpbar to prevent strange overlaying and some CSS-hacks (if helpbar is opened — change margin-left of the suggester).
It's easy, but I didn't do it, cause we still waiting for mock-ups of panel look from the designer....
=> Make Inspector scrollable

packages/xod-client/src/core/styles/components/PatchGroup.scss, packages/xod-client/src/core/styles/components/PatchTypeSelector.scss, packages/xod-client/src/core/styles/components/ProjectBrowser.scss, packages/xod-client/src/core/styles/components/Sidebar.scss, packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
It fixes #840.
It's a bit hacky (using `calc` in the CSS), but to avoid using `calc` we have to rewrite few components and make a HOC from FocusTrap... Cause that is a large amount of work, I fixed it this way.
If you have any ideas how to avoid using `calc` without big refactoring — feel free to write a comment :)
=> Fix resizing of project browser on window resize

package.json, packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx, workspace/__lib__/xod/core/format-number/any.cpp
Few hotfixes in a single PR:
* Forgot to migrate `format-number` node implementation to the new string interface
* Remove a forgotten `console.log`. It showed up as a warning and thus passed the CI
* Enforce linter to treat warnings as errors
=> Fix format-number C++ implementation, enforce linter

CHANGELOG.md, workspace/__lib__/xod/core/watch/any.cpp
Now it is a compile error to try to cast a string to bool.
P.S> We should really employ compilation tests in CI
=> Fix `watch` node C++ implementation for the new string interface

packages/xod-client/src/editor/actions.js
Closes #886
Looks like a regression after some rebase. 🤔
It was ok in #861
=> Fix broken isInput check when copying

docs/reference/supported-hardware/index.yaml, workspace/__lib__/xod/bits/bcd-to-dec/patch.xodp, workspace/__lib__/xod/bits/bitwise-and/patch.cpp, workspace/__lib__/xod/bits/bitwise-and/patch.xodp, workspace/__lib__/xod/bits/bitwise-not/patch.cpp, workspace/__lib__/xod/bits/bitwise-not/patch.xodp, workspace/__lib__/xod/bits/bitwise-or/patch.cpp, workspace/__lib__/xod/bits/bitwise-or/patch.xodp, workspace/__lib__/xod/bits/bitwise-xor/patch.cpp, workspace/__lib__/xod/bits/bitwise-xor/patch.xodp, workspace/__lib__/xod/bits/dec-to-bcd/patch.xodp, workspace/__lib__/xod/bits/project.xod, workspace/__lib__/xod/bits/shift-left/patch.cpp, workspace/__lib__/xod/bits/shift-left/patch.xodp, workspace/__lib__/xod/bits/shift-right/patch.cpp, workspace/__lib__/xod/bits/shift-right/patch.xodp, workspace/__lib__/xod/common-hardware/ds1307-rtc-read/patch.xodp, workspace/__lib__/xod/common-hardware/ds1307-rtc-write/patch.xodp
The PR brings support for popular real-time clock ICs: DS1307 and compatible.
To implement register encoding and decoding, low-level bitwise operations were required. So a new `xod/bits` library was implemented.
=> Add nodes for DS1307 RTC reading and writing

workspace/__lib__/xod/common-hardware/sd-log/patch.cpp
That what happens if not tested properly on real tasks.
An attempt to make a simple SD logger exposed two very silly bugs.
=> Fix sd-log node: append, not overwrite; noop without a pulse

.circleci/Dockerfile, .circleci/config.yml
Can’t go on with Travis. Emergency migration to Circle CI. Things yet to be done:
- C++ tests
- Badge
- Remove Travis
But even without them, we can battle-test CircleCI side-by-side with Travis enabled (will disable strict requirement for Travis status check)
=> Setup Circle CI

CHANGELOG.md
* [ide] Add a feature to install libraries right from IDE. Hit “File → Add Library”, enter a name as seen at https://xod.io/libs/, and you’re ready to use new nodes.
* [ide] Add a feature to publish your project as a library. Hit “File → Publish Library” and you’re done. See your library at https://xod.io/libs/.  Others can immediately install it for themselves.
* [ide] Add account pane to login/logout from within IDE. Hit “View → Toggle Account Pane” to access it. Login is required to publish a library.
* [ide] Embed C++ editor for low-level nodes. Double-click a `not-implemented-in-xod` node to open and edit the code.
* [ide] Click and drag for bulk selection with a marquee. Move, copy, paste, delete faster. Drag from left to right to select only items completely covered by the …
=> Update changelog for upcoming 0.16.0

.circleci/config.yml
=> Apply GCS Content-Disposition metadata while distro upload from CircleCI

packages/xod-arduino/src/transpiler.js, packages/xod-arduino/test/transpiler.spec.js
Local patches used to get C++ namespace names containing `@` symbol which is illegal
in C++ identifiers.
It made impossible to have a native patch in the project being transpiled.
=> Fix code generation when native patches implemented locally

CHANGELOG.md
* [ide] Patch crafting optimized. Performance gain is ~35%
* [core] Fix code generation for C\++ nodes local to the current project: no more `@` symbols in the code
* [ide] Trigger library search when a library name is pasted from the clipboard
* [ide] Fix regression of macOS auto-update failure introduced in 0.16.0
* [ide] Fix patch board break when trying to drag-n-drop the patch node on itself or adjacent UI elements
* [ide] Fix embedded code editor overflow past the window boundaries when source code is too long
* [ide] Handle network connection problems gracefully while authorization and library publishing
* [ide] Escape regular expression symbols while searching for a node (thanks @awgrover)
* [ide] In the account pane, send credentials on Enter press
=> Prepare changelog for upcoming 0.16.1

packages/xod-client/.storybook/config.js, packages/xod-client/.storybook/webpack.config.js, packages/xod-client/package.json, packages/xod-client/stories/Button.jsx, packages/xod-client/stories/Comment.jsx, packages/xod-client/stories/Debugger.jsx, packages/xod-client/stories/Inspector.jsx, packages/xod-client/stories/Link.jsx, packages/xod-client/stories/Menubar.jsx, packages/xod-client/stories/Modals.jsx, packages/xod-client/stories/PatchDocs.jsx, packages/xod-client/stories/PatchGroup.jsx, packages/xod-client/stories/PatchGroupItem.jsx, packages/xod-client/stories/PatchTypeSelector.jsx, packages/xod-client/stories/Pin.jsx, packages/xod-client/stories/PinLabel.jsx, packages/xod-client/stories/SnackBarMessage.jsx, packages/xod-client/stories/Suggester.jsx, yarn.lock
Because the version we were using is _really_ outdated.
Also, this PR could serve as a preview of upgrading to webpack 3 (take a look at `packages/xod-client/.storybook/webpack.config.js`) 😉
=> Upgrade storybook

packages/xod-client/src/core/styles/components/Helpbox.scss, packages/xod-client/src/editor/containers/Helpbox.jsx, packages/xod-client/src/editor/reducer.js, packages/xod-client/src/editor/utils.js, packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
But now Helpbox will render to the left of a referred element if it could not fit the window width.
E.G. Helpbox renders fine for right-sided ProjectBrowser.
I'm not sure that `rightSided` is a good name for this, maybe it should be `leftSided` or something else. Open to suggestions.
=> Tweak Helpbox positioning (right-sided)

packages/xod-arduino/src/getTokens.js, packages/xod-arduino/src/index.js, packages/xod-client/src/core/styles/abstracts/colors.scss, packages/xod-client/src/core/styles/components/CodeMirror.scss, packages/xod-client/src/editor/codemirrorXodMode.js, packages/xod-client/src/editor/components/CppImplementationEditor.jsx
It will highlights:
* Types from XOD (`Number`, `State`, `XString` and etc),
* Built-in functions (`getValue`, `setTimeout` and etc),
* Special keywords (`GENERATED_CODE`, `input_$$$` and etc)
* Some built-in functions from Arduino (`digitalRead`, `pinMode` and etc), that are approved by XOD Team (for example, synchronous functions which will lead to a holdup of running transactions, like `delay()`, is not included)
=> Add code highlighting in Cpp Editor

packages/xod-cli/package.json, packages/xod-pm/package.json, yarn.lock
Fixes spammy warnings: `Parameter 'orgname' is ambiguous because the
defined spec has more than one parameter with the name: 'orgname' and
the passed-in parameter values did not define an 'in' value.`
See: https://github.com/swagger-api/swagger-js/pull/1197
=> Update swagger client version to the latest

packages/xod-client/src/core/styles/components/CustomScroll.scss
=> Remove opacity transitions from CustomScroll to defeat moire in help boxes

packages/xod-client/src/core/styles/components/Debugger.scss, packages/xod-client/src/debugger/reducer.js, packages/xod-client/stories/Debugger.jsx
Closes #988
Works okay as a quick fix(in very rare cases there might be a slight jitter when scrolling), but in the future we should find another solution, because `react-infinite` assumes that all elements in the list have equal height.
=> Don’t truncate log lines

packages/xod-client/src/core/styles/components/HelpPanel.scss, packages/xod-client/src/core/styles/components/Helpbox.scss, packages/xod-client/src/editor/actions.js, packages/xod-client/src/editor/components/PatchDocs.jsx
It closes #1000.
Also, I tweak styles of cursors inside QuickHelp and Helpbox to change it more accurately to `text` (not everywhere, only on text),
=> Fix copy text from Quick Help

packages/xod-client-electron/package.json, packages/xod-client-electron/src/app/arduinoActions.js, packages/xod-client-electron/src/app/main.js, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/styles/components/Debugger.scss, packages/xod-client/src/debugger/messages.js, packages/xod-client/src/debugger/reducer.js, packages/xod-client/src/debugger/state.js, packages/xod-client/src/debugger/utils.js, yarn.lock
This PR contains several small tweaks related to Deployment panel:
=> Deployment panel tweaks

packages/xod-client/src/editor/actions.js, packages/xod-client/src/editor/utils.js, packages/xod-client/src/project/reducer.js, packages/xod-client/src/project/utils.js, packages/xod-project/src/constants.js, packages/xod-project/src/flatten.js, packages/xod-project/test/flatten.spec.js
Closes #969
Closes #998
Ideally, `not-implemented-in-xod` node and implementation attachment should be a single entity, but for now measures taken in this PR should be enough.
=> Fix disparity between `not-implemented-in-xod` node and attached implementation

packages/xod-client-electron/package.json, yarn.lock
Electron has a known critical severity security vulnerability in version range >= 1.6.0,< 1.6.16 and should be updated.
=> Bump electron version

packages/xod-client-electron/src/app/main.js
Works on Windows and macOS.
Opened by the application via JumpList or dock menu, respectively.
=> Add a list of recent documents

CHANGELOG.md
* [core] Perform loop unroll optimization technique for the generated C\++ code. It dramatically improves RAM consumption and XOD execution performance.  (thanks, @awgrover).
* [ide] Eight new embedded tutorial chapters (21 through 28) explaining pulse basics and LCD interaction.
* [ide] Support Markdown in patch comments. Your patches now can be more expressive. See the tutorial project for example.
* [ide] Add OS file associations for `*.xodball`, `project.xod`, `*.xodp` and a list of recent items in the app system menu. Currently works on Windows and macOS, not Linux yet.
* [ide] You’re not limited now in where on file system you save a project.  Previously a project was saved in a “workspace,” now you may choose an arbitrary directory with the native OS “Save” dialog.
* [ide] Blur the …
=> Update changelog for upcoming 0.18.0

packages/xod-client-electron/test-func/0-fs.spec.js, packages/xod-client-electron/test-func/pageObject.js
Sometimes functional tests fail while waiting for `PatchGroup--installing`. But we have an assumption that library sometimes installs so fast, that DOM element has no time to appear... Now we'll wait for the message, cause message appeared for some time in any case.
=> Fix functional test to make it more solid

packages/xod-fs/src/load.js, packages/xod-pm/test-func/mocha.opts
Bug appeared somewhere in PR #1050 or later in one of the fixes 😬 
What was wrong: after loading project from xodball and merging it with library nodes, it doesn't resolve node types inside library patches.
Now it fixed and it will not break library patches after opening a xodball anymore.
=> Fix open of xodball breaks library patches

packages/xod-deploy/test-func/mocha.opts
Semi-fixes the `xod-deploy` functional tests which involve the cloud compiler.
=> Increase test timeouts to fight flakes

packages/xod-client/src/project/components/Node.jsx, packages/xod-client/src/tooltip/components/Tooltip.jsx
It was like this before custom tooltips:
https://github.com/xodio/xod/blob/22819700d2a82fbb3c28b08682ac1a8d2ef0ca23/packages/xod-client/src/project/components/Node.jsx#L106
=> Don’t show tooltip for dragged node

packages/xod-client/src/core/styles/components/Node.scss, packages/xod-client/src/core/styles/components/Pin.scss, packages/xod-client/src/editor/components/NodeInspector.jsx, packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/BoolPinWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/DeadPinWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/NumberPinWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinIcon.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PulsePinWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx, packages/xod-client/src/editor/containers/Patch/index.jsx, packages/xod-client/src/editor/containers/Patch/modes/panning.jsx, packages/xod-client/src/editor/nodeHoverContextType.js, packages/xod-client/src/project/components/Node.jsx, packages/xod-client/src/project/components/NodePinsOverlay.jsx, packages/xod-client/src/project/components/layers/NodesLayer.jsx, packages/xod-client/src/project/components/nodeParts/VariadicHandle.jsx, packages/xod-client/src/tooltip/components/TooltipHOC.jsx
There is no issue. 😬 
What I've done:
- Show variadic PinDots on hover, on selection or while changing arity level
- Make Node hovering works not by CSS, but by using React context and state. Now Node still rendered as hovered while User moving mouse over Pins
- Show PinDots in Inspector
- Show PinDots in Help box
- Tweak variadic Node grip (6px width -> 5px, added 0.5px to x to avoid smooth edge)
- Fixed React Warning of `TooltipHOC` on dragging Node (introduced in PR #1094 )
You can check out this PR commit by commit.
Please, pay attention to the first commit, cause there is appeared using of React context.
=> Show variadic pin dots on hover

workspace/__lib__/xod/core/discretize/patch.xodp, workspace/__lib__/xod/core/project.xod
Thanks to @gweimer for noticing this.
=> Remove unneeded output pin from xod/core/discretize

workspace/__lib__/xod/core/defer-pulse/patch.cpp
Fixes the problem [reported on forum](https://forum.xod.io/t/state-machine-initialization-in-xod-0-18-1/499). I introduced the bug in #1020
=> Do not emit extraneous pulse from defer-pulse on boot

packages/xod-client/src/project/actions.js, packages/xod-client/src/projectBrowser/components/ProjectBrowserPopups.jsx, packages/xod-client/src/utils/components/PopupPrompt.jsx, packages/xod-client/src/utils/inputFormatting.js, packages/xod-project/src/constants.js, packages/xod-project/src/internal/patchPathUtils.js, packages/xod-project/src/patchPathUtils.js, packages/xod-project/test/fixtures/blinking.xodball, packages/xod-project/test/patchPathUtils.spec.js, packages/xod-project/test/project.spec.js
It closes #1114.
Also tweaked rename popup. Now input already contains current patch name and autoselected.
=> Legalize parametric patch names

packages/xod-arduino/src/transpiler.js, packages/xod-client/src/core/containers/App.jsx, packages/xod-client/src/project/components/Link.jsx, packages/xod-client/src/project/components/layers/LinksOverlayLayer.jsx, packages/xod-client/src/project/selectors.js, packages/xod-project/src/constants.js, packages/xod-project/src/flatten.js, packages/xod-project/src/func-tools.js, packages/xod-project/src/messages.js, packages/xod-project/src/project.js, packages/xod-project/src/utils.js, packages/xod-project/test/flatten.spec.js, packages/xod-project/test/project.spec.js
It closes #1118.
And fixes #999.
Xodball for testing: [broken-link.xodball.zip](https://github.com/xodio/xod/files/1811826/broken-link.xodball.zip)
Also, in this PR appeared:
- tooltips for "dead reference" links. Check it out: [deadref.xodball.zip](https://github.com/xodio/xod/files/1816376/deadref.xodball.zip)
- errors with titles from `xod-project` (try to "show code" in both xodballs)
=> Mark links between incompatible types

packages/xod-client-electron/src/app/main.js, packages/xod-client/src/core/styles/components/Suggester.scss, packages/xod-client/src/editor/containers/Helpbox.jsx
Now one can make 1-to-1 snapshots of XOD IDE for publications on Medium and in the docs. Working with such a narrow window made a couple of layout bugs in the suggester apparent. They are fixed now.
=> Support 700px IDE window width

packages/xod-client/src/core/styles/components/Pin.scss, packages/xod-client/src/project/components/Pin.jsx
It adds a small marker on generic pins with deduced types.
=> Add generic markers to the generic Pins

packages/xod-project/src/messages.js, packages/xod-project/src/patch.js, packages/xod-project/src/project.js, packages/xod-project/src/typeDeduction.js, packages/xod-project/src/types.js, packages/xod-project/src/utils.js, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-bound-nongenerics.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-variadics.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.xodball, packages/xod-project/test/patch.spec.js, packages/xod-project/test/typeDeduction.spec.js, packages/xod-project/test/utils.spec.js
- rebind compatible values when changing node type
- replace "flatten and then resolve" algorithm with a recursive one
- solves the problem with generic variadic patches composed from other generic patches
- allows more precise error messages(prerequisite for #1122)
- get rid of `PatchSignature` stuff
=> Refactor abstract nodes resolution

packages/xod-project/src/legacy.js, workspace/__lib__/xod/core/analog-input/patch.xodp, workspace/__lib__/xod/core/branch/patch.xodp, workspace/__lib__/xod/core/clock/patch.xodp, workspace/__lib__/xod/core/constant-number/patch.xodp, workspace/__lib__/xod/core/constant-string/patch.xodp, workspace/__lib__/xod/core/greater/patch.xodp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/lcd-time/main/patch.xodp
There was a bug: boundValue could contain an empty string, even if it's a bound value for boolean terminal Pin. So we have just to omit empty strings from bound values.
There is no regression, cause:
- empty strings were valid only for strings and this is a default value
- all other types should contain another values
=> Fix: omit empty strings from bound literals

CHANGELOG.md
* [core] Implement generic nodes. Such nodes may work with values type of which is not known in advance. See the user’s guide to learn more.
* [core] Values of any type bound to pins are now stored as-is using strings. As a good side effect, one may now bind scientific notation numbers (`3e-6` for `0.000003`), infinity (`+Inf`, `-Inf`), and `NaN` in the Inspector. Strings are now always enquoted. When you deal with regular (non-generic) pins, the required quotes will be added for you automatically. (#1164)
* [ide] Allow relinking of occupied input pins. Now instead of showing an error, IDE removes the existing link, replacing it with the new one. (#1120)
* [ide] Preserve window position and size across launches. (#1134)
* [ide] The main window now can be as small as 700px in width. It …
=> Update changelog for upcoming 0.20.0

.circleci/config.yml
Otherwise, when building dists, some important tools are left out.
=> Always install devDependencies in CI

packages/xod-project/src/project.js
There is no issue 😬 
Bug produced in the PR #1175
=> Fix crashing IDE on opening project with nodes from not installed libs

packages/xod-project/src/typeDeduction.js, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-abstracts-inside-regular.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-bound-nongenerics.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-variadics.xodball, packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved.xodball, packages/xod-project/test/typeDeduction.spec.js
Fixes a quite nasty problem reported on our forum.
Main changes are in `packages/xod-project/src/typeDeduction.js`, the rest are fixtures/tests.
=> Resolve abstract nodes placed deeply inside regular patches

packages/xod-project/src/messages.js, packages/xod-project/src/patch.js, packages/xod-project/test/patch.spec.js
Fixes a bug that was [reported on our forum](https://forum.xod.io/t/xod-0-20-1-issue/751)
Bug could be reproduced by placing `variadic-1` node in a patch like this one:
[troublesome-variadic.xodball.zip](https://github.com/xodio/xod/files/1983331/troublesome-variadic.xodball.zip)
=> Fix crash when constructing message about wrong variadic pin types

packages/xod-client-electron/src/shared/errorFormatter.js, packages/xod-client-electron/src/view/containers/App.jsx
Fixes #1080 
The root cause is `ERROR_FORMATTERS` had an impossible type. Some values were strings, other were objects. A non-uniform typing became a source of troubles, again. Please, don’t use such magic in your code: if something can’t have a sane signature it is wrong and should be rewritten.
=> Fix [Object object] in deploy pane messages

packages/xod-client-browser/src/containers/App.jsx
There is no issue. 😬 
Minor bug, that does not corrupts IDE, but logs an error in the developers console.
**To reproduce:**
1. Open browser IDE
2. Click "File"->"Open Project..." and load any .xodball (it changes a value of the input and next time when User cancel selection of file it will fire the callback)
3. Click "File" -> "Open Project..." again. But then cancel opening.
You'll see an error in the DevTools.
=> Fix canceling of open project in browser ide causes exception

packages/xod-project/src/legacy.js, packages/xod-project/test/legacy.spec.js
Some old bound values ("false" on pulses) was not converted into new literal "Never". This PR fixes it.
It's a part (1/2) of critical bug [reported on the forum](https://forum.xod.io/t/problem-xod-0-20-2/774).
The second half of the problem is about new bundled `xod/core` and old `xod/core` saved in the `user-workspace/__libs__` folder.
=> Fix bound value migration for pulses

packages/xod-arduino/src/transpiler.js
There is no issue. But it's a critical bug 😬 
If you make some Node that have few unnamed output ports — it will fail in C++ compilation, cause linked Nodes points to not normalized pin label (`output_OUT` instead of `output_OUT1`, `output_OUT2` and so on).
=> Fix bug in the transpilation: wrong output pin labels

.circleci/Dockerfile, .circleci/config.yml, package.json, packages/xod-client-browser/Dockerfile, packages/xod-project/Dockerfile
The PR adds docker image build & push for the browser IDE along with distros building. After merging it we will be able to release from any branch, specifically we are going to create a Git-flow stable branch to release from regardless of the state of `master`.
Also, this PR places a restriction on prerelease naming. Now the valid prefixes are:
- `prerelease-patch-` — creates canary release bumping the patch number
- `prerelease-minor-` — creates canary release bumping the minor number as it was before
The `prerelease-` prefix alone is no longer enough to schedule a prerelease.
=> Add IDE docker images building on release

packages/xod-client/src/project/selectors.js, packages/xod-func-tools/src/index.js, packages/xod-func-tools/src/sets.js, packages/xod-project/src/patch.js, packages/xod-project/src/typeDeduction.js
It tweaks IDE performance, that was reduced in the v0.20.0 by adding generic types and type deduction.
The same as https://github.com/xodio/xod/pull/1211
But based on another branch (0.20.x)
=> Tweak performance of type deduction

packages/xod-client/src/utils/normalizeGenericValue.js
Fixes #1221
Problem was introduced in #1192 and does not affect `0.20.x`.
=> Allow unbinding generic values in inspector

packages/xod-client/src/project/selectors.js, packages/xod-client/src/projectBrowser/selectors.js, packages/xod-func-tools/src/objects.js, packages/xod-func-tools/src/sets.js, packages/xod-project/src/index.js, packages/xod-project/src/patch.js, packages/xod-project/src/typeDeduction.js, packages/xod-project/test/patch.spec.js
Still tweaks IDE performance, that was reduced in the v0.20.0 by adding generic types and type deduction.
=> Optimize memoized selector comparators

.circleci/config.yml, packages/xod-cli/src/xodc-tabtest.js, packages/xod-cli/src/xodc.js, packages/xod-tabtest/cpp/Makefile, packages/xod-tabtest/src/Holes/Holes_Map_String.re, packages/xod-tabtest/src/Holes/Holes_Map_String.rei, packages/xod-tabtest/src/Tabtest.re, packages/xod-tabtest/src/Tabtest.rei, packages/xod-tabtest/src/Tabtest_Js.re, packages/xod-tabtest/src/XodProject/Attachment.re, packages/xod-tabtest/src/XodProject/Attachment.rei, packages/xod-tabtest/src/XodProject/Patch.re, packages/xod-tabtest/src/XodProject/Patch.rei, packages/xod-tabtest/src/XodProject/PatchPath.re, packages/xod-tabtest/src/XodProject/PatchPath.rei, packages/xod-tabtest/src/XodProject/Project.re, packages/xod-tabtest/src/XodProject/Project.rei, packages/xod-tabtest/test/Holes_Map_String_jest.re
- Closes #1227 
- Adds support to test a whole XOD project, not a particular patch
- Adds `xodc tabtest --output-dir=/path/to/dir` switch
- Adds `xodc tabtest --no-build` switch
=> Run tabular tests when doing CI

CHANGELOG.md
* [build] Fix macOS distro download filename. Now it has proper `.dmg` extension. (#1198)
* [core] Fix opening projects saved prior to 0.20.0 with some pins explicitly bound to `Never`. Notably, the bug led to a transpilation error when using `digital-output` from own `xod/core` fork. (#1207)
* [core] Fix untitled outputs name assignment for C\++. Previously, all untitled outputs got name `output_OUT`. Now they are `output_OUT1`, `output_OUT2`, and so on. (#1204)
* [core] Fix C\++ generation from generic nodes containing `not-implemented-in-xod` which previously was silently failing. (#1225)
* [ide] Minimize performance regression in 0.20.x caused by generics resolution (#1213, #1214)
* [ide] Fix occasional `[Object object]` errors when deploying. Now they are still there but formatted …
=> Update changelog for upcoming 0.20.3

packages/xod-client/src/editor/actions.js, packages/xod-client/src/project/selectors.js, packages/xod-client/src/project/utils.js, packages/xod-project/src/project.js
When double-clicking on missing patch current version of IDE crashes.
Here is a xodball to reproduce the issue: [missing-patch.xodball.zip](https://github.com/xodio/xod/files/2030601/missing-patch.xodball.zip)
=> Fix IDE crash when opening missing patch

packages/xod-client/src/project/reducer.js, packages/xod-project/src/index.js
Previously project description, version, license etc persisted when user created new project via `File -> New Project...`
=> Reset metadata when creating new project

packages/xod-arduino/src/templates.js
There is no issue, but it could be a problem for some boards...
Transpile analog ports into `A#` instead of `PIN_A#`, cause some boards do not have defined `PIN_A#`. Need a proof? See `pins_arduino.h` for Arduino Due.
=> Fix transpiling analog ports into another C++ literals

packages/xod-client/src/core/styles/abstracts/variables.scss
Playing with new `gpio` made it obvious that the current blue color for type Port is easily confused with Pulse. Our UX designer suggested green for ports in the old mockups. We even have it’s definition (`$green`), but don’t use anyhow.
Well, it can be confused with a number. But it’s much better than pulse confusion as it is semantically close to a number. We use the number to emulate the port type after all. Also, we have a few statements about the greenness of PORT pins in the tutorial. So, I suggest making ports $green:
=> Make port type color green

workspace/__lib__/xod/core/i2c-begin-transmission/patch.xodp, workspace/__lib__/xod/core/i2c-end-transmission/patch.xodp, workspace/__lib__/xod/core/i2c-read/patch.xodp, workspace/__lib__/xod/core/i2c-request-bytes-6/patch.xodp, workspace/__lib__/xod/core/i2c-request/patch.xodp, workspace/__lib__/xod/core/i2c-send-byte/patch.xodp, workspace/__lib__/xod/core/i2c-send-bytes-2/patch.xodp, workspace/__lib__/xod/core/i2c-write/patch.xodp, workspace/__lib__/xod/i2c/begin-transmission/patch.cpp, workspace/__lib__/xod/i2c/begin-transmission/patch.xodp, workspace/__lib__/xod/i2c/end-transmission/patch.cpp, workspace/__lib__/xod/i2c/end-transmission/patch.xodp, workspace/__lib__/xod/i2c/i2c/patch.cpp, workspace/__lib__/xod/i2c/i2c/patch.xodp, workspace/__lib__/xod/i2c/project.xod, workspace/__lib__/xod/i2c/read-byte/patch.cpp, workspace/__lib__/xod/i2c/read-byte/patch.xodp, workspace/__lib__/xod/i2c/request/patch.cpp, workspace/__lib__/xod/i2c/request/patch.xodp, workspace/__lib__/xod/i2c/write-byte/patch.cpp, workspace/__lib__/xod/i2c/write-byte/patch.xodp
=> Extract I2C-related nodes of standard library to `xod/i2c`

workspace/__lib__/xod/i2c/request/patch.xodp
In #1256 I used to change `N` of `i2c/request` from Byte to Number and forgot to fix the default bound value. It was `1h` which translates to C++ as is and cause a compile error
=> Fix bad literal value for i2c/request, input N

CHANGELOG.md
* [core] Add a custom type system which allows defining own complex types. (#1216, #1224)
* [core] Add a new built-in type: `Port`. Port specifies a board hardware pin like `A4` or `D4`. Port specification became more straightforward rather than plain numbers used before. (#1232)
* [core] Add a new built-in type: `Byte`. A byte is a group of eight bits specified in a binary or hexadecimal form. (#1192)
* [core] Clarify error messages related to generic type conflicts. (#1246)
* [nodes] Add byte-to-number and number-to-byte conversion nodes to  [`xod/bits`](https://xod.io/libs/xod/bits/). (#1186)
* [nodes] Make nodes in `xod/bits` use the new Byte type. (#1261)
* [nodes] Make nodes in `xod/common-hardware` use the new Byte and Port types. They now also expose unified pins for an explicit …
=> Update changelog for upcoming 0.21.0

packages/xod-pm/test-func/fetch.spec.js
It changed after publishing stdlib for version 0.21.0
=> Update expected dependencies list of xod/common-hardware in xod-pm func tests

packages/xod-client-electron/src/shared/messages.js, packages/xod-client-electron/src/upload/messages.js, packages/xod-client-electron/src/view/actions.js, packages/xod-client-electron/src/view/autoupdate.js, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/crashReporterMiddleware.js, packages/xod-client/src/editor/messages.js, packages/xod-client/src/messages/actions.js, packages/xod-client/src/project/messages.js, packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
=> Make snack bar messages persistent by default

packages/xod-client-electron/src/view/actions.js, packages/xod-client-electron/src/view/containers/App.jsx
Just stop asking User for switch workspace and extend save/load error messages with a note, provided from original error.
Also, wanted to refactor error messages on failed save/load project, cause now some messages are old-fashioned (with "errorCodes") mixed with new-fashioned messages. So sometimes error message looks ugly (like "NOT_A_JSON {"input":{}}") or shows error message twice. But on a small part of this job I understood that is too large. So I stashed it for the future. 😬
=> Do not request switch workspace on any save/load error

workspace/__lib__/xod/common-hardware/lps331-barometer/patch.xodp, workspace/__lib__/xod/common-hardware/st-barometer-read-pressure-raw/patch.xodp, workspace/__lib__/xod/common-hardware/st-barometer-read-tmp-raw/patch.xodp, workspace/__lib__/xod/common-hardware/st-barometer-write-register/patch.xodp, workspace/__lib__/xod/core/pressure-to-altitude/patch.xodp
New common hardware library "lps331-barometer" for a barometer based on lps331 chip by ST.
- Communicates via I2C;
- Outputs temperature in Celsius;
- Outputs pressure in Pa;
New core utility "pressure-to-altitude"
- Convert a pressure in pascals to an altitude above the sea level in meters;
=> New common hardware library for a lps331 barometer

packages/xod-client/src/utils/normalizeByte.js, packages/xod-client/test/normalizeByte.spec.js
Before:
`15abc` -> `15d`
`7C` -> `7d`
Now:
`15abc` -> `00h`
`7C` -> `00h`
=> Make normalizeByte reject invalid integer values

workspace/__lib__/xod/math/log-bx/patch.xodp
`divide` is in `xod/core`, not `xod/math`
=> Correct reference to divide node in xod/math/log-bx

docs/reference/data-types/README.md, packages/xod-arduino/src/templates.js, packages/xod-client/src/utils/normalizeByte.js, packages/xod-client/test/normalizeByte.spec.js, packages/xod-project/src/utils.js, packages/xod-project/test/utils.spec.js
Now in addition to hex, dec and bin literals, you can bind chars into `byte` inputs in the form `'a'` or `'\n'`. Should be very handy for processing strings.
=> Char literal for byte type

packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/trackLastSavedChanges.js
After #1282 desktop IDE was always thinking that there are unsaved changes
=> Fix tracking of unsaved changes in desktop IDE

packages/xod-client/package.json, packages/xod-client/src/core/styles/components/CustomScroll.scss, packages/xod-client/src/core/styles/components/Sidebar.scss, packages/xod-client/src/editor/components/SuggesterContainer.jsx, yarn.lock
It's an addition to PR #1339.
Did update `react-custom-scroll` and tweak styles.
Tested on Ubuntu 18.04 (FF, Chrome, Electron).
=> Improve hiding of protruding scrollbars

packages/xod-arduino/platform/program.tpl.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
=> Wrap output pin values with pragmas only once

CHANGELOG.md
* [ide] Most of the error messages appearing on the snackbar made persistent, that is they don’t hide automatically. (#1284)
* [ide] Better reject invalid literals in the inspector for byte values. (#1313)
* [core] Now a character surrounded by single quotes (`'G'`) is a valid byte literal which denotes a corresponding value from the ASCII table. (#1317)
* [core] Make some error messages more clear and consistent (#1330).
* [ide] Add View menu items to toggle the project browser and inspector (#1340).
* [ide] Allow links between inputs and outputs of the same node. It will transpile successfully if the node contains a `defer` on the loop path inside it. (#1349).
* [`xod/core/length(string)`](https://xod.io/libs/xod/core/length(string))
* …
=> Update changelog for upcoming 0.22.0

packages/xod-project/src/internal/patchPathUtils.js, packages/xod-project/src/patch.js, packages/xod-project/src/patchPathUtils.js, packages/xod-project/test/patch.spec.js, packages/xod-project/test/patchPathUtils.spec.js
Duplicate labels in expanded variadics are totally expected, for example: https://github.com/xodio/xod/blob/master/packages/xod-project/test/fixtures/expanding.expected.xodball
Bug was introduced in #1356
=> Skip clashing pin labels check for expanded variadic patches

packages/xod-client/src/debugger/containers/DebuggerTopPane.jsx
My bad. It was introduced in the PR #1374 🙈
=> Get rid of React warning in DebuggerTopPane

packages/xod-client/src/core/styles/components/Node.scss
The bug was introduced by me in PR #1375 😬
=> Avoid superfluous word clipping in node labels

packages/xod-client/src/editor/components/Suggester.jsx, packages/xod-client/src/editor/containers/Editor.jsx, packages/xod-client/src/hinting/actionType.js, packages/xod-client/src/hinting/actionTypes.js, packages/xod-client/src/hinting/actionUtils.js, packages/xod-client/src/hinting/actions.js, packages/xod-client/src/hinting/errorCollectors.js, packages/xod-client/src/hinting/middleware.js, packages/xod-client/src/hinting/patchSearchData.js, packages/xod-client/src/hinting/reducer.js, packages/xod-client/src/hinting/selectors.js, packages/xod-client/src/hinting/state.js, packages/xod-client/src/hinting/typeDeduction.js, packages/xod-client/src/hinting/validation.internal.js, packages/xod-client/src/hinting/validation.js, packages/xod-client/src/project/actions.js, packages/xod-client/src/project/reducer.js, packages/xod-client/src/project/selectors.js, packages/xod-client/test/hinting.spec.js, packages/xod-patch-search/src/index.js, packages/xod-patch-search/test/index.spec.js, packages/xod-project/src/node.js
It optimizes the patch search engine by:
- move patch search data into `hinting` branch of the state and update it by middleware, instead of selectors
- update patch search data only on some actions (like `PATCH_DESCRIPTION_UPDATE` or `PROJECT_OPEN`).
- and update search data partially if it possible (updates only patch description, rename patch or add the new one — update only its search data).
- make `searchPatches` function pure and memoize it once
- Suggester component shows only 20 best search results
- Suggester searches when User types at least two symbols
In numbers:
- **Every change** on the patch will not call updating patch search index: ~53ms -> 0ms
- Little changes (description, rename, add): ~53ms -> ~2.5ms
- Change of the entire set of the patches …
=> Optimize patch search and suggester

packages/xod-client/src/hinting/reducer.js, packages/xod-client/test/fixtures/broken-project-with-custom-types.xodball, packages/xod-client/test/hinting.spec.js
It closes #1405.
Broken type deduction was just a symptom of the problem that spread to other branches as well.
Introduced by me in the previous PR #1404.
=> Fix updating of hinting branches

packages/xod-client-browser/src/containers/App.jsx
I found this bug when I test XOD in the browser version.
**How to reproduce**
1. Open a browser version of XOD IDE
2. Open some xodball
3. Make any change
4. Try to open the same xodball
**Expected**
It opens...
**Actual**
Nothing changed.
=> Make possible to reopen project with the same file path in browser IDE

CHANGELOG.md
* [core] The buses concept is introduced. (#1392, #1397)
* [ide] Dramatic optimizations while working with patches and debugging: moving nodes, binding values, creating links, searching for nodes, watching values, etc. (#1396, #1400, #1402, #1404)
* [ide] Show constant nodes’ values as their labels unless overriden rather than static `constant-number`, `constant-string`, etc. (#1366)
* [ide] Do not auto-stop a debug session on patch changes, show a note about the change instead. (#1374)
* [ide] Split deployment pane output into several tabs dedicated to Compiler, Uploader, and Debugger. (#1409)
* [ide] Make constant and watch nodes resizable like comments. (#1375)
* [core] Comment out XOD pragmas in C\++ code so that GCC produces no compilation warnings. (#1360)
* [core] Detect and report …
=> Update changelog for upcoming 0.23.0

packages/xod-client/src/core/styles/components/Node.scss
It fixes #1417.
But one important thing, without margins at all it still not fit "WWWW" 😬
=> Fix label margins to fit labels with four characters

packages/xod-client/package.json, packages/xod-client/src/editor/containers/Patch/index.jsx, packages/xod-client/src/editor/containers/Patch/modes/acceptingDraggedPatch.jsx, packages/xod-client/src/editor/containers/Patch/modes/changingArityLevel.jsx, packages/xod-client/src/editor/containers/Patch/modes/debugging.jsx, packages/xod-client/src/editor/containers/Patch/modes/linking.jsx, packages/xod-client/src/editor/containers/Patch/modes/marqueeSelecting.jsx, packages/xod-client/src/editor/containers/Patch/modes/moving.jsx, packages/xod-client/src/editor/containers/Patch/modes/panning.jsx, packages/xod-client/src/editor/containers/Patch/modes/resizingComment.jsx, packages/xod-client/src/editor/containers/Patch/modes/resizingNode.jsx, packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx, packages/xod-client/src/project/selectors.js, yarn.lock
=> Scroll patch with mouse wheel or trackpad

appveyor.yml, packages/xod-client-electron/package.json, tools/appveyor.ps1, yarn.lock
`electron-updater` is set to exactly `3.0.3` because of https://github.com/electron-userland/electron-builder/issues/3269
Also switches to node 10 in appveyor build(which is the last bit of #1419)
=> Upgrade to latest electron-builder

workspace/__lib__/xod/uart/begin/patch.xodp, workspace/__lib__/xod/uart/example-print/patch.xodp, workspace/__lib__/xod/uart/example-read/patch.xodp, workspace/__lib__/xod/uart/example-uart/patch.xodp, workspace/__lib__/xod/uart/example-write/patch.xodp, workspace/__lib__/xod/uart/soft-uart/patch.cpp, workspace/__lib__/xod/uart/soft-uart/patch.xodp, workspace/__lib__/xod/uart/uart-0/patch.cpp, workspace/__lib__/xod/uart/uart-0/patch.xodp, workspace/__lib__/xod/uart/uart-1/patch.cpp, workspace/__lib__/xod/uart/uart-1/patch.xodp, workspace/__lib__/xod/uart/uart-2/patch.cpp, workspace/__lib__/xod/uart/uart-2/patch.xodp, workspace/__lib__/xod/uart/uart-3/patch.cpp, workspace/__lib__/xod/uart/uart-3/patch.xodp, workspace/__lib__/xod/uart/uart-usb/patch.cpp, workspace/__lib__/xod/uart/uart-usb/patch.xodp, workspace/__lib__/xod/uart/uart/patch.cpp, workspace/__lib__/xod/uart/uart/patch.xodp
Example patches are also updated.
=> Deprecate xod/uart/begin, call begin right in constructor nodes

CHANGELOG.md
* [core] Implemented the `#pragma XOD require` directive. Now a XOD library author can declare a dependency on a regular Arduino C++ library hosted on GitHub. It will be automatically downloaded and installed for library users. (#1425, #1426)
* [core] Optimize one of the transpilation stages: topological graph sorting. For complex projects, it brings 10 to 100× faster transpilation. (#1430)
* [ide] A patch can now be scrolled with mouse scroll or the scroll gesture on a laptop touchpad. (#1412)
* [nodes] `xod/uart/uart-*` constructor nodes now initialize the interface on their own. No need to use the `begin` node separately. (#1442)
* [chore] Upgrade to NodeJS v10 and the latest Electron Builder. It gives slightly better performance and will bring much faster and traffic-saving IDE …
=> Update changelog for upcoming 0.24.0

tools/update-docs-screenshots.sh
`readlink` haven't flag `-f` on MacOS.
And it is not needed unless we run it through a symlink.
So I just replaced it with `$0`.
=> Fix screenshoter script for docs to run properly on MacOS

packages/xod-client-electron/package.json, packages/xod-client-electron/src/app/utils.js
This issue [was reported on our forum](https://forum.xod.io/t/0-24-upgrade-fail/1130).
Because `__ardulib__` directory was packed into `asar`, it was unreachable by build tools.
=> Make bundled __ardulibs__ reachable again

workspace/__lib__/xod/common-hardware/servo/patch.cpp, workspace/__lib__/xod/gpio/digital-read/patch.cpp, workspace/__lib__/xod/gpio/digital-write/patch.cpp, workspace/__lib__/xod/gpio/pwm-write/patch.cpp, workspace/blink/__fixtures__/arduino.cpp
It never is. It's `uint8_t`:
https://github.com/xodio/xod/blob/5934f2b56eaeac8cb0f7b38b80e99d2e9303bc4f/packages/xod-arduino/src/templates.js#L77
=> Stop checking if port is less than zero

workspace/__lib__/xod-dev/esp8266-mcu/example-get-external-ip/patch.xodp
No more distracting user with `uart`-related nodes.
Also, removes extra space from `pass-from-sequence` SEQ that should not be there.
=> Make xod-dev/esp8266-mcu/example-get-external-ip more clear

workspace/__lib__/xod-dev/esp8266-mcu/http-request(esp8266-mcu-inet)/patch.xodp
Now it does not start a new request until the previous one completes.
Here is a visual diff:
before
after
=> Make http-request(esp8266-mcu) more resillient

packages/xod-project/src/pin.js, packages/xod-project/test/pin.spec.js
=> Correctly induce variadic labels for pins with numeric labels

CHANGELOG.md
* [c++] Make the runtime code compatible with ESP8266 MCUs. (#1456, #1460)
* [ide] Employ `arduino-cli` for hardware packages installing, compiling, and uploading. It makes possible to use the same variety of target boards which Arduino IDE supports. In other words, you can install third-party hardware packages to be used by XOD. In particular, ESP8266-based boards like WEMOS and NodeMCU board index is included out of the box. (#1459, #1465, #1469)
* [ide] Rather than silently starting to download a potentially big hardware package on the first upload, an explicit offer to download and install is shown. The download process is visualized with the progress bar. (#1459)
* [ide] Add a new item to the Deploy menu to upgrade already installed toolchains to their latest versions. As a …
=> Update changelog for upcoming 0.25.0

packages/xod-client-browser/src/containers/App.jsx
A very small tweak.
The previous behavior caused some pain when creating quick projects in browser IDE, because it would save it as just `.xodball`, which was not correctly  associated with XOD IDE.
=> Provide default name for xodball saved from browser IDE

packages/xod-client-electron/src/app/arduinoCli.js, packages/xod-client-electron/src/upload/messages.js, packages/xod-client-electron/src/view/containers/App.jsx
=> Make proper errors for different steps of upload process

packages/arduino-cli/README.md, packages/arduino-cli/src/config.js, packages/arduino-cli/src/index.js, packages/arduino-cli/test-func/index.spec.js, packages/xod-client-electron/src/app/arduinoCli.js, packages/xod-client-electron/src/app/main.js, packages/xod-client-electron/src/app/migrateArduinoPackages.js
Previously, when the user switched workspace and then tried to upload something onto the board or install package — arduino-cli works with the old workspace instead of newly selected one.
This PR make arduino-cli works always with the current user's workspace.
When he switches it — it changes arduino-cli `.cli-config.yml`.
=> Change arduino-cli config on switch workspace

CHANGELOG.md
* [ide] Fix bug in upload options parser, which prevented uploading on Arduino Pro and Pro Mini (#1481)
* [c++] Do not rely on NUM_DIGITAL_PINS constant, which is not defined for some boards (#1482)
* [ide] Make proper errors for different steps of upload process (#1484)
* [ide] Fixed a bug with workspace switching when installed packages were used from initial workspace (#1475)
* [ide] Put missing ampersand in the "Upgrade Arduino Packages & Toolchains" menu item (#1483)
=> Update changelog for upcoming 0.25.1

packages/xod-client-electron/src/app/subscribeIpc.js
While some process that communicates through IPC using `promifisyIpc` and `subscribeIpc` modules is running it tries to send process/success/failure messages to the renderer from the main process. For example, installing arduino C++ libraries, arduino packages, upload to the board and etc.
So when User closes IDE while a process is running it causes exception, cause the main process can't send data to the renderer, that was destroyed.
Fortunately, electron developers added a method `event.sender.isDestroyed()`, so we can avoid sending data to the destroyed process. That I did in this PR and it fixes the bug.
**How to reproduce the bug**
1. Open previous IDE version.
2. Start installation of some arduino package.
3. Close the window before it's done.
4. You'll see an exception in the OS …
=> Fix exception on close of IDE

packages/xod-patch-search/test/index.spec.js, workspace/__lib__/xod-dev/sharp-irm/gp2y0a-linearize/patch.xodp, workspace/__lib__/xod-dev/sharp-irm/gp2y0a02-range-meter/patch.xodp, workspace/__lib__/xod-dev/sharp-irm/gp2y0a21-range-meter/patch.xodp, workspace/__lib__/xod-dev/sharp-irm/gp2y0a41-range-meter/patch.xodp, workspace/__lib__/xod-dev/sharp-irm/project.xod, workspace/__lib__/xod/common-hardware/gp2y0a-linearize/patch.xodp, workspace/__lib__/xod/common-hardware/gp2y0a02-range-meter/patch.xodp, workspace/__lib__/xod/common-hardware/gp2y0a21-range-meter/patch.xodp, workspace/__lib__/xod/common-hardware/gp2y0a41-range-meter/patch.xodp
PR refers to the [XEN-L005](https://github.com/xodio/xod-xens/tree/master/XEN-L005)
- Transfers range meter nodes for Sharp devices to the new `xod-dev/sharp-irm` library;
- Deprecates the previous Sharp nodes at the `xod/common-hardware` library.
- For new nodes, adds the analog reference voltage adjustment.
=> Sharp Infrared Range Meters Library

packages/xod-deploy/src/serialport.js
It causes issues with some boards using CP2102 USB to Serial chip
=> Don't raise DTR when opening serialport on windows

packages/xod-client-browser/src/containers/App.jsx, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/containers/App.jsx, packages/xod-client/src/editor/actions.js, packages/xod-client/src/editor/containers/Patch/index.jsx, packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx, packages/xod-client/src/utils/browser.js, packages/xod-client/src/utils/constants.js, packages/xod-client/src/utils/menu.js
It fixes #1497.
Also, I've added "Select All" menu item into browser version of the IDE, that selects all entities on the Patch.
=> Select all patch entities or input contents from menu item

packages/xod-arduino/platform/runtime.cpp, packages/xod-client/src/utils/normalizePort.js, packages/xod-project/src/utils.js, packages/xod-project/test/utils.spec.js, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
- Add ability to define PORTs as `PA13`, `PB8` etc
- Don't redefine `dtostrf`, [the built-in one](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/avr/dtostrf.c) is fine
=> Make sure generated C++ is compatible with STM32 boards

packages/xod-client/src/utils/components/Menubar.jsx
It fixes #1515.
The bug was caused by `float: right` of hotkey label element, which was placed after the block contents.
=> Fixes hotkey label position in the main menu

packages/arduino-cli/README.md, packages/arduino-cli/src/config.js, packages/arduino-cli/src/index.js, packages/arduino-cli/src/listAvailableBoards.js, packages/arduino-cli/test-func/index.spec.js, packages/arduino-cli/test-func/listAvailableBoards.spec.js, packages/xod-client-electron/src/app/arduinoCli.js, packages/xod-client-electron/src/app/arduinoDependencies.js, packages/xod-client-electron/src/arduinoDependencies/middleware.js, packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx, packages/xod-client-electron/src/upload/messages.js, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client-electron/src/view/formatError.js
Now it will show an error message and remove new URLs from `.cli-config.yml` that could cause errors (but left downloaded files in the `__packages__` directory to make possible to inspect what is really went wrong).
So IDE will be usable after the error.
It fixes #1506
=> Handle package indexes update fails

packages/xod-client-electron/src/app/arduinoCli.js
No issue.
This should be done in the #1509 
This fix does not affect on getting URLs from `extra.txt`, but when we do `ensureExtraTxt` it writes bundled URLs if they do not exist in the file.
This PR make contents of `extra.txt` looks correctly in the text editor on any platforms.
=> Fix joining urls in extra.txt with os-specific EOL instead of `\n`

CHANGELOG.md
* [ide] Do not hide any output from the compiler and uploader in the deployment pane. (#1490, #1502)
* [ide] Fix regression: bring back the message on a successful upload. (#1491)
* [ide] Fix ugly hover color of message and header buttons. (#1492)
* [ide] Fix the scroll position when Deployment pane is opened for the first time. (#1494)
* [nodes] Fix `clock` hang if the `EN` pin is constantly updated. (#1496)
* [ide] Gracefully shutdown long background processes like package installing when quitting XOD IDE. (#1500, #1523)
* [ide] Ensure Edit → Select All and its keyboard shortcut work properly on all OS’es and browsers. (#1505)
* [ide] Do not raise DTR when opening a serial port on Windows. It caused issues with some boards using the CP2102 USB-to-Serial chip. (#1507)
* [c++] Make port …
=> Update changelog for upcoming 0.25.2

packages/xod-client-electron/src/app/main.js
Proposed change: do not check for update on not supported platforms. This prevents exception and useless stack traces in the console.
=> Prevent autoupdate on not supported platforms

.circleci/config.yml, packages/xod-cli/src/commands/tabtest.js, packages/xod-cli/test/tabtest.spec.js
Remove the output tabtest directory if `--clean` flag is set.
Why not do this by default? Because Pete can set output directory to ~.
Special feature for @brusherru
=> xod-cli: tabtests in separate directories, clean before run

packages/xod-client-electron/src/view/containers/App.jsx
=> Fix "Select All" hotkey in Desktop IDE

packages/xod-client-electron/package.json
This caused problems with auto-update on Windows.
See https://github.com/electron-userland/electron-builder/issues/1187#issuecomment-278972073
=> Fix publisherName to match certificate's "Issued to" field

package.json, yarn.lock
The version we used before is 3.6.2:
https://github.com/xodio/xod/blob/28b13bb70b95cf8e48e9f0184ac385a41ca333ac/yarn.lock#L10296-L10297
which is `node-sass`'s dependency: https://github.com/xodio/xod/blob/master/yarn.lock#L10444
It is quite old and among others has [this issue](https://github.com/nodejs/node-gyp/pull/1455) that causes lots of pain on fresh macOS versions.
=> Explicitly use fresh node-gyp

packages/xod-client-electron/package.json
In #1555 we replaced it with a new one, but having both is a more bulletproof solution.
=> Add second publisherName for electron-builder config

packages/xod-cli/test-func/mocha.opts, packages/xod-client-electron/src/app/main.js, packages/xod-deploy-bin/src/arduinoCli.js
The bug was introduced here: https://github.com/xodio/xod/pull/1548 (forgotten argument).
Also, a functional test of `xod-cli` fails on my machine by timeout, so I enlarged it.
=> Fix workspace creation

packages/xod-arduino/src/index.js, packages/xod-arduino/src/messages.js, packages/xod-arduino/src/transpiler.js, packages/xod-arduino/test/transpiler.spec.js, packages/xod-client/src/core/formatErrorMessage.js
=> Add missing formatter for error about too many outputs

workspace/__lib__/xod/core/constant-boolean/patch.xodp, workspace/__lib__/xod/core/constant-byte/patch.xodp, workspace/__lib__/xod/core/constant-number/patch.xodp, workspace/__lib__/xod/core/constant-port/patch.xodp, workspace/__lib__/xod/core/constant-string/patch.xodp, workspace/__lib__/xod/core/length(string)/patch.xodp, workspace/__lib__/xod/core/sine-wave/patch.xodp, workspace/__lib__/xod/core/square-wave/patch.xodp
We have some holes in `xod/core` which are apparent when looking at https://xod.io/libs/xod/core/
=> Add missing xod/core node descriptions

packages/xod-func-tools/src/Errors.re, packages/xod-func-tools/src/Errors.rei, packages/xod-tabtest/src/SpecialColumns.re, packages/xod-tabtest/src/TabData.re, packages/xod-tabtest/src/TabData.rei, packages/xod-tabtest/src/Tabtest.re, packages/xod-tabtest/src/Validator.re, packages/xod-tabtest/src/Validator.rei, packages/xod-tabtest/test/TabData_jest.re, packages/xod-tabtest/test/Validator_jest.re
Now it throws errors if tabtest:
- does not have columns for some pins (missing pin labels)
- have redundant pins, that are missing in tested node
- have duplicated pin labels
And it works fine with "special" columns, like `__time(ms)`.
Also, I've added `List.contains` and `List.difference` into `belt-holes` package.
=> Add pin labels validation in tabtests

package.json, packages/xod-deploy/src/libraryManager.js, yarn.lock
=> Fix error on successful arduino libs installation

packages/xod-tabtest/cpp/main.cpp, packages/xod-tabtest/src/Tabtest.re, vendor/catch2/catch.hpp
Catch2 updated to version v2.5.0 (can compile to emscripten).
Catch2 configuration tweaks (fast compilation - 20% faster).
Fix problem with namespacing for XStrings.
=> update catch2 and fix tabtest namespacing

workspace/__lib__/xod/core/modulo/patch.test.tsv
I'm writing an article about writing tabular tests and use `modulo` as an example.
=> Improve tabtest of `xod/core/modulo`

packages/xod-client-electron/src/settings/components/PopupSetWorkspace.jsx, packages/xod-client/src/core/styles/components/SkyLight.scss
It fixes #1596 
Also, fixed click outside the closable popup (on the shaded overlay) will cause closing too.
=> Fix closing of Switch Workspace Popup and click outside the popup

CHANGELOG.md
* [ide] Introduce tabtests — an instrument to test patches. See https://xod.io/docs/guide/testing-patches/ for details (#1585, #1602)
* [ide] Improve UX of installing Arduino packages (#1581)
* [nodes] `xod-dev/sharp-irm` library for Sharp Infrared Range Meters. Deprecates previous Sharp nodes from `xod/common-hardware` (#1493)
* [ide] Make double-click on a constant node focus the field for editing its value in the Inspector (#1599)
* [nodes] Add a pin to explicitly set connection timeout to `xod-dev/esp8266-mcu/connect` (#1595)
* [nodes] Make `xod/core/buffer` generic (#1495)
* [ide] Provide default name for xodball saved from browser IDE (#1474)
* [cli] A major overhaul of `xodc` tool. See `xod-cli`'s README for details (#1518)
* [ide] Fix Switch Workspace Popup that was unclosable …
=> Update changelog for upcoming 0.26.0

packages/xod-cli/src/commands/publish.js
Just found a stupid error.
Unfortunately, it is difficult to test without http requests recording.
=> Fix publishing of new lib by xod-cli

packages/arduino-cli/package.json
Dry run output:
```
npm notice 📦  arduino-cli@0.26.0
npm notice === Tarball Contents === 
npm notice 819B   package.json                   
npm notice 9.1kB  README.md                      
npm notice 2.4kB  dist/config.js                 
npm notice 3.2kB  dist/config.js.map             
npm notice 5.0kB  dist/cpuParser.js              
npm notice 8.5kB  dist/cpuParser.js.map          
npm notice 6.0kB  dist/index.js                  
npm notice 11.2kB dist/index.js.map              
npm notice 3.3kB  dist/listAvailableBoards.js    
npm notice 5.1kB  dist/listAvailableBoards.js.map
npm notice 6.2kB  dist/optionParser.js           
npm notice 10.0kB dist/optionParser.js.map       
npm notice 1.3kB  dist/parseProgressLog.js       
npm notice 2.3kB  dist/parseProgressLog.js.map   
npm …
```
=> Prepare arduino-cli wrapper for publishing

packages/xod-client-browser/test-func/pageObjects/PromptPopup.js
But very often we get failed errors with this selector. I hope it helps to avoid reruns...
Will rerun tests a few times to be sure it helped :)
=> Enlarge timeout for selector that mostly fails function tests

packages/xod-project/src/flatten.js
This will prevent issues caused by "stranded" `patch.cpp` files.
Partially solves #1609. The fact that "stranded" `patch.cpp` files appear is a [separate issue](#1618), but it's a bit too big to be tackled right before New Year holidays😁
=> When flattening, check that patch is leaf by presence of niix marker instead of attachment

packages/xod-client/src/hinting/actions.js, packages/xod-client/src/hinting/middleware.js, packages/xod-client/src/hinting/patchMarkers.js, packages/xod-client/src/hinting/reducer.js, packages/xod-client/src/hinting/selectors.js, packages/xod-client/src/hinting/state.js, packages/xod-client/src/projectBrowser/selectors.js
It fixes #1547 
It adds `patchFlags` map into `hinting` state.
Fulfilling this map on loading project takes about 35ms on my machine and takes less 1ms on any change, including adding/pasting/deleting marker nodes.
=> Add patchFlags map into hinting state to fix #1547

packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/platform/runtime.cpp, packages/xod-arduino/src/templates.js, packages/xod-project/src/patchPathUtils.js, workspace/__lib__/xod/debug/tweak-boolean/patch.cpp, workspace/__lib__/xod/debug/tweak-boolean/patch.xodp, workspace/__lib__/xod/debug/tweak-byte/patch.cpp, workspace/__lib__/xod/debug/tweak-byte/patch.xodp, workspace/__lib__/xod/debug/tweak-number/patch.cpp, workspace/__lib__/xod/debug/tweak-number/patch.xodp, workspace/__lib__/xod/debug/tweak-pulse/patch.cpp, workspace/__lib__/xod/debug/tweak-pulse/patch.xodp, workspace/__lib__/xod/debug/tweak-string-16/patch.cpp, workspace/__lib__/xod/debug/tweak-string-16/patch.xodp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
Would appreciate feedback about messages format (do we need to begin them with some unique symbol to avoid consuming _all_ serial input?)
=> C++ implementation for tweak nodes

packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/platform/runtime.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
=> Tweak nodes in Simulation

CHANGELOG.md
* [c++, ide] Add ability to simulate a program without uploading it to a board (#1661)
* [nodes, c++, ide] Add `xod/debug/tweak-*` nodes whose values can be adjusted right from the IDE during debug and simulation sessions (#1662, #1665, #1666)
* [ide] Add ability to connect to a board by serial at any time (#1660)
* [nodes] Move exising debug-related nodes (`watch` and `console-log`) from `xod/core` to `xod/debug` library (#1657)
* [ide] Add tooltips for show/hide sidebar pane buttons (#1658)
* [ide] Make a fancy look for `xod/patch-nodes/jumper` (#1659)
* [nodes] Fix prescision and overflow issues with `format-number` and `cast-to-string(number)` nodes (#1650, #1652, #1669)
=> Update changelog for upcoming 0.27.0

workspace/__lib__/xod/math/abs/patch.cpp
`abs` casts input value to `int` :(
=> Make `xod/math/abs` correctly handle values between -1 and 0 on esp8266

packages/xod-project/built-in-patches.xodball, packages/xod-project/src/project.js, packages/xod-project/tools/loadBuiltinPatches.js
Closes #1647, #1427
Also, generates descriptions for custom type terminals.
From now on, all built-in type terminals must be listed in `built-in-patches.xodball`. Otherwise, a build-time error will occur.
=> Add meta- and generated nodes descriptions

packages/xod-client-browser/test-func/creatingBlinkPatch.spec.js, packages/xod-client/src/core/styles/abstracts/colors.scss, packages/xod-client/src/core/styles/abstracts/variables.scss, packages/xod-client/src/core/styles/components/Comment.scss, packages/xod-client/src/core/styles/components/Inspector.scss, packages/xod-client/src/core/styles/components/Node.scss, packages/xod-client/src/core/styles/components/PatchDocs.scss, packages/xod-client/src/core/styles/components/Pin.scss, packages/xod-client/src/core/styles/components/PinLabel.scss, packages/xod-client/src/core/styles/components/PinValue.scss, packages/xod-client/src/core/styles/components/PopupPublishProject.scss, packages/xod-client/src/core/styles/main.scss, packages/xod-client/src/editor/components/PatchDocs.jsx, packages/xod-client/src/project/components/Node.jsx, packages/xod-client/src/project/components/PatchSVG.jsx, packages/xod-client/src/project/components/Pin.jsx, packages/xod-client/src/project/components/PinLabel.jsx, packages/xod-client/src/project/components/PinOverlay.jsx, packages/xod-client/src/project/components/PinValue.jsx, packages/xod-client/src/project/components/layers/BackgroundLayer.jsx, packages/xod-client/src/project/components/nodeParts/BusNodeBody.jsx, packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx, packages/xod-client/src/project/components/nodeParts/TerminalNodeBody.jsx, packages/xod-client/src/project/components/nodeParts/VariadicHandle.jsx, packages/xod-client/src/project/nodeLayout.js
=> New look of patch board with bound values

packages/xod-arduino/src/transpiler.js, packages/xod-project/src/constants.js, packages/xod-project/src/index.js, packages/xod-project/src/patch.js, packages/xod-project/src/project.js, packages/xod-project/test/patch.spec.js, packages/xod-project/test/project.spec.js
Before debug-nodes were removed only from the top level.
It could cause compilation error when uploading without debug.
=> Remove debug nodes from nested patches

packages/xod-client/package.json, packages/xod-client/src/editor/components/TabsItem.jsx, packages/xod-client/src/editor/containers/Tabs.jsx, yarn.lock
=> Close tabs on middle click

packages/xod-client/package.json, packages/xod-client/src/core/styles/abstracts/variables.scss, packages/xod-client/src/core/styles/components/Editor.scss, packages/xod-client/src/core/styles/components/ProjectBrowser.scss, packages/xod-client/src/core/styles/components/Sidebar.scss, packages/xod-client/src/core/styles/components/Tabs.scss, packages/xod-client/src/core/styles/components/TabsContainer.scss, packages/xod-client/src/core/styles/components/Workarea.scss, packages/xod-client/src/editor/components/TabsContainer.jsx, packages/xod-client/src/editor/components/TabsItem.jsx, packages/xod-client/src/editor/containers/Editor.jsx, packages/xod-client/src/editor/containers/Tabs.jsx, yarn.lock
=> Make tabline scrollable

workspace/__lib__/xod/math/map-clip/patch.test.tsv, workspace/__lib__/xod/math/map-clip/patch.xodp, workspace/__lib__/xod/math/max/patch.test.tsv, workspace/__lib__/xod/math/max/patch.xodp, workspace/__lib__/xod/math/min/patch.test.tsv, workspace/__lib__/xod/math/min/patch.xodp
also tweak `xod/math/map-clip` to output correct values when target range bounds are reversed
=> Add xod/math/min and xod/math/max

workspace/__lib__/xod/core/integrate-dt/patch.test.tsv, workspace/__lib__/xod/core/integrate-dt/patch.xodp
Kinda very useful node to the `xod/core` library.
Gonna use it a second time in my projects.
I'm sure that XOD should support it. 
What do you think?
=> Add `xod/core/integrate-dt` 

packages/xod-client/src/core/styles/components/Node.scss, packages/xod-client/src/project/components/nodeParts/JumperNodeBody.jsx
=> Fix coloring of jumper node when it’s connected to generic pins

packages/xod-client/src/utils/normalizeByte.js
=> Prevent `0bh` byte literal from being converted to `00000000b`

packages/xod-client/src/editor/containers/Patch/modes/moving.jsx, packages/xod-client/src/editor/containers/Patch/modes/resizingNode.jsx
=> Move links during node resize

packages/xod-client/src/editor/containers/Patch/modes/resizingComment.jsx, packages/xod-client/src/editor/containers/Patch/modes/resizingNode.jsx, packages/xod-client/src/project/nodeLayout.js
Fix few bugs introduced in PR #1695:
- split links with buses
- resizing nodes and comments
=> Fix bus link splitting and nodes/comment resizing

packages/xod-client/src/editor/containers/Patch/modes/panning.jsx
Otherwise when the user finishes panning, the viewport is teleported to outer space.
=> Convert offset to slots when panning by holding spacebar or middle mouse button

CHANGELOG.md
* [ide] Improve patch board design that shows bound values (#1684)
* [ide] Make sure nodes and comments are always aligned to slots grid (#1695)
* [ide] Show a list of available inputs/outputs in QuickHelp when C++ or tabtest editors are open (#1682)
* [ide] Make tabline scrollable if too many tabs are open (#1694)
* [ide] Close tabs on middle click (#1686)
* [nodes] Add descriptions to all `xod/patch-nodes` and auto-generated terminals for custom types (#1685)
* [`xod/debug/tweak-pulse`](https://xod.io/libs/xod/debug/tweak-pulse/) (#1701)
* [`xod/math/min`](https://xod.io/libs/xod/math/min/) and [`xod/math/max`](https://xod.io/libs/xod/math/max/) (#1700)
* [`xod/core/integrate-dt`](https://xod.io/libs/xod/core/integrate-dt/) (#1590)
* [ide] Fix links looking detached when resizing watch …
=> Update changelog for upcoming 0.28.0

tools/screenshot-xodball
There is no issue. But here is the example of the bug:
=> Fix docs screenshoter to avoid hovering effects

packages/xod-client/src/editor/containers/Patch/modes/linking.jsx, packages/xod-client/src/project/reducer.js
There is no issue. Reported by @gabbapeople in the chat
To reproduce:
- Start linking
- Press "B" to place a bus node
Expected to see a new bus node at the mouse position.
Actually, it placed somewhere outside the view area.
=> Fix adding a bus node while linking in the right position

packages/xod-client/src/core/styles/abstracts/variables.scss
This should deal with readability issues that were reported on our forum: https://forum.xod.io/t/xod-0-28-0-more-detailed-patch-board/1961/6?u=evgenykochetkov
=> Make node and pin labels a bit brighter

packages/xod-client/src/debugger/reducer.js
Otherwise, when rerunning a simulation of the same patch, stale values from the previous simulation are displayed.
[stale-values-on-simulation-rerun-example.xodball.zip](https://github.com/xodio/xod/files/2995801/stale-values-on-simulation-rerun-example.xodball.zip)
=> Clean watchNodeValues when simulation is stopped

packages/xod-client/src/workers/wasm.worker.js
We have hardcoded name of wasm file. But this name baked in the JS runtime on the backend at compilation time. So we need a hack that rewrites this name in JS runtime.
Сontrariwise, it's always only one wasm file. So we can just always return URL of the wasm file. 
This change is backward compatible with the current backend version.
=> Allow custom name of wasm file

workspace/__lib__/xod/core/word-to-number/patch.xodp
It was introduced in v0.13.
Now we have `xod/bits/i16-to-number` that does exactly the same.
=> Deprecate `xod/core/word-to-number`

tools/screenshot-xodball
There is no issue. But this is a very handy tool for auto-generating new tutorial docs from a xodball.
Also, we can remove manually specified height from most of the `update-screenshots.sh` to make the same paddings on all screenshots.
=> Docs screenshotter auto-detects patch height if it's not specified by User

tools/generate-tutorial-docs.js
Run:
`./tools/generate-tutorial-docs.js 2.0.0 /path/to/welcome-to-xod /output/path/to/docs/tutorial [--no-screenshots]`
`2.0.0` is the version that will be in each README.md metadata
An optional flag `--no-screenshots` will generate a screnshotter script but will not run it.
It will be placed in the same output directory, next to the modified `welcome-to-xod.xodball` (without comments).
Also, you can place `before-1st-h2.md` in the directory of the tutorial article (next to `README.md`). The tool will glue it into the article right before the first H2.
=> Add tool that generates tutorial docs from welcome-to-xod project

tools/generate-tutorial-docs.js, tools/screenshot-xodball
1. `generate-tutorial-docs` outputs wrong paths in the `update-screenshots.sh`. Fixed.
2. `screenshot-xodball` hangs when tried to make a screenshot for the empty patch. Fixed.
=> Fix screenshot tools

workspace/__lib__/xod/mutex/project.xod
=> Fix lib name for `xod/mutex`

CHANGELOG.md
* [ide] Reworked built-in tutorial that covers all the new features (#1731, #1735, #1743, #1745, #1750, #1753)
* [ide] Mark libraries and projects with red icons if they contain errors (#1752)
* [xod/mutex](https://xod.io/libs/xod/mutex) — a library to works with mutually exclusive resources. Used to avoid conflicts between nodes controlling long-running processes. (#1748)
* [xod-dev/servo](https://xod.io/libs/xod-dev/servo) — a library to work with RC hobby servos (#1748)
* Add [animation-unit](https://xod.io/libs/xod/core/animation-unit) and [animation-segment](https://xod.io/libs/xod/core/animation-segment) nodes to `xod/core` (#1748)
* Add `tweak-string-32`, `tweak-string-64` and `tweak-string-128` nodes to [xod/debug](https://xod.io/libs/xod/debug) (#1738)
* [ide] Prevent displaying …
=> Update changelog for upcoming 0.29.0

workspace/__lib__/xod-dev/servo/servo-device/patch.cpp, workspace/__lib__/xod/core/animation-unit/patch.cpp
Introduced in #1748.
Causes errors when compiling for esp8266 and some other platforms.
=> Fix C++ errors/warnings in new nodes

workspace/__lib__/xod-dev/servo/project.xod, workspace/__lib__/xod/mutex/project.xod, workspace/__lib__/xod/net/project.xod, workspace/__lib__/xod/stream/project.xod
=> Add missing descriptions to `xod-dev/servo`, `xod-mutex`, `xod-net` and `xod/stream` libraries

workspace/__lib__/xod/common-hardware/st-imu-generic-sensor/patch.xodp
`xod/common-hardware/lis331dlh-accelerometer`, `xod/common-hardware/lis331hh-accelerometer` and `xod/common-hardware/lis3dh-accelerometer` were affected
=> Prevent race condition on initialisation in xod/common-hardware/st-imu-generic-sensor

packages/xod-client/src/core/styles/components/AccountPane.scss, packages/xod-client/src/user/components/AuthForm.jsx, packages/xod-client/src/user/containers/AccountPane.jsx
"Daily quotas" phrase doesn't represent the essence of our time slot based limits. Also, we always say "limits" or "cloud limits" and not "quotas". But actually I'm not againts "quotas", I'm against "daily". So, If you know a more appropriate phrase, propose it :)
=> Rename daily quotas to cloud limits (cosmetic)

packages/xod-client/src/utils/normalizeErrcode.js, packages/xod-client/test/normalizeErrcode.spec.js, packages/xod-project/src/utils.js, packages/xod-project/test/utils.spec.js
They were limited to 127 before because the last was intended to be used as a flag. This is no longer true, so we can use all 8 bits to store the errcode.
=> Allow Errcode values up to 255

packages/xod-arduino/package.json, packages/xod-client-electron/package.json
It fixes #1803.
It reduces the file size:
- MacOS App: 365.4MB -> 237MB
- .dmg: 123.5MB -> 87.9MB
- Windows Installer: 95.8MB -> 61.2MB
- Linux rpm: 69.1MB -> 56.4MB
- Linux deb: 72.5MB -> 56.2MB
In average excluding of `bs-platform` and excessive `xod-arduino` files reduces size for 32% 😎
=> Exclude the whole bs-platform from bundling into electron app

workspace/__lib__/xod-dev/servo/servo-device/patch.xodp
To follow a path of the least surprise I’ve changed the default servo pulse width limits to be exactly as in the Arduino Servo library. There’s no standard which clearly defines the pulse limits for hobby servos, so both variants are magic. But the 544/2400 magic matches the magic for people coming from Arduino IDE and supports servos capable to do a 180° turn.
=> Make servo pulse limits match Arduino defaults

packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js, packages/xod-client/src/debugger/selectors.js, packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
There is no issue, but there was a bug.
1. Create patch `a`
2. Place two `tweak-number`s inside
3. Place two `output-number`s
4. Link outputs and tweaks
5. Create patch `b`
6. Place node `a` with linked `watch` node
7. Run simulation or upload with debug
8. Drill down and change a value on each tweak to different values
Everything works fine.
One of the tweaks affects the nearest one. Because of both of them sends data with "undefined" instead of valid node id, which parsed in C++ as `0`. So both of them affects the value of the tweak node with `0` id.
=> Fix sending data from the nested tweaks

CHANGELOG.md
* [core] The errors mechanism. (#1777, #1784, #1818)
* [ide] Errors are visualized in XOD IDE during the simulation and debug. (#1797)
* [ide] Cancel the restriction of deleting terminals in use. Now, this is allowed and will cause the patches which use the terminal to become broken which is quickly fixable by undoing the deletion or removing the offending links. (#1809)
* [ide] Upgrade the underlying UI Electron platform from 1.8 to 4.2 which makes IDE a bit more responsive and brings Gtk3 on Linux. (#1811)
* [ide] Link to amperka.com on the welcome banner. Should we have some profit after all! (#1820)
* [nodes] The `ERR` pulses gone from the standard library in favor of using the errors. (#1808)
* [nodes] `xod/core/if-else` is now truly generic and works with any types. (#1767)
* …
=> Update changelog for upcoming 0.30.0

workspace/__lib__/xod/i2c/read-byte/patch.xodp
=> Remove one stale mention of error code from `i2c/read-byte`

workspace/__lib__/xod/core/error(pulse)/patch.cpp, workspace/__lib__/xod/core/has-error(pulse)/patch.cpp, workspace/__lib__/xod/core/has-error(pulse)/patch.xodp, workspace/__lib__/xod/core/if-error(pulse)/patch.cpp, workspace/__lib__/xod/core/if-error(pulse)/patch.xodp
In short, not all nodes that handle errors (`if-error`, `has-error`) worked correctly with a pulse type. Even the `error(pulse)` node did not work correctly.
Here is an example project:  [test-pulse-errors.xodball.zip](https://github.com/xodio/xod/files/3406640/test-pulse-errors.xodball.zip)
=> Fix and add nodes that works with errored pulses

workspace/__lib__/xod-dev/esp8266-mcu/example-get-data-from-dweet/patch.xodp, workspace/__lib__/xod-dev/w5500/example-get-data-from-dweet/patch.xodp
There is no issue. Fixes that new `led` node has no pulse input anymore.
=> Remove broken links to `led` nodes

packages/xod-cloud-compile/package.json, packages/xod-deploy-bin/package.json, packages/xod-deploy/package.json, packages/xod-fs/package.json
For `xod-cloud-compile`, `xod-deploy-bin`, `xod-deploy` and `xod-fs`
Related to #1843
=> Add missing “files” fileds in package.json

packages/xod-tabtest/src/Tabtest.re
No more guessing which line caused a test to fail!
=> Wrap tabtests code into sections

workspace/__lib__/xod/core/act/patch.xodp
I switched the specialization for testing purposes (to avoid conflict between `@/pulse-on-change` and `xod/core/pulse-on-change`) and then forget to switch it back 🙈 
Fixed.
=> Fix `xod/core/act` node

CHANGELOG.md
Here is the added part:
* [core] Do not store node id for error raisers and save 2 bytes of RAM for each error raiser node. (#1841)
* [core] Optimize transaction state keeping (#1850)
* [core] Make port type castable to string type (#1857)
* [core] Wrap tabtests code into sections (#1860)
* [core] Change error clear conditions (#1858)
* [nodes] BREAKING :exclamation: Replace `UPD` inputs pins on idempotent actuator nodes with the `ACT` input pin: [xod-dev/servo/servo](https://xod.io/libs/xod-dev/servo/servo/), [xod/common-hardware/h-bridge-dc-motor](https://xod.io/libs/xod/common-hardware/h-bridge-dc-motor/), [xod/common-hardware/led](https://xod.io/libs/xod/common-hardware/led/). (#1842)
* [ide] Highlight a few more core functions in C++ editor (#1859)
* …
=> Prepare changelog for 0.31.0 version

workspace/__lib__/xod/debug/stream-string/patch.cpp
Old implementation works only once on the boot.
This one will stream the string on the change. So now this node can be used with `tweak-string` or any other dynamically changed input value.
Example: 
❗️ 
Probably, it should be moved to `xod/stream` and should not be a utility node anymore.
What do you think?
=> Tweak `xod/debug/stream-string` node

packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/src/templates.js, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
The issue was reported [on our forum](https://forum.xod.io/t/xod-0-31-0-released-standard-library-improvements/2643/5).
=> Fix a bug that caused compilation error if a defer node was used in a feedback loop without an upstream error raiser

workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-20x4/patch.xodp
Error noted by @gabbapeople, produced by me 😬 
Missing links between `act` nodes and `print-at` nodes of second, third and fourth lines.
=> Fix quickstart node for 20x4 I2C text LCD

CHANGELOG.md
* [core] Fix a bug that caused compilation error if a defer node was used in a feedback loop without an upstream error raiser (#1871)
* [core] Fix updating of package indexes and bundle the latest one (#1869)
* [nodes] Fix quickstart node for 20x4 I2C text LCD in `xod-dev/text-lcd` library (#1875)
* [nodes] Fix wrong types in `xod-dev/dht` library (#1877)
* [core] Fix errors not propagating through defer nodes in some edge cases (#1873)
* [nodes] Fix debounce time in `xod/common-hardware/button` (#1880)
=> Update changelog for upcoming 0.31.1

packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/containers/App.jsx, packages/xod-client/src/debugger/actions.js, packages/xod-client/src/debugger/reducer.js, packages/xod-client/src/debugger/selectors.js, packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js, packages/xod-client/src/debugger/state.js, packages/xod-client/src/editor/actions.js, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
There is no issue. Probably it is an overlooked part of the previously closed issues: #1882
Also, it fixes a bug introduced in the #1888 — do not remove the leading quote in a string mode (already quoted by "virtual" quotes).
=> Make tweak nodes works fine with the new literals like `=XOD_PROJECT`

workspace/__lib__/xod/i2c/read-byte/patch.cpp
Reading the `0x00` byte value from I2C should not provide XOD error.
Here is an example:
https://forum.xod.io/t/rtc-ds3231-cant-dispay-plain-hours-eg-12-00/2923
Originally the `virtual int read(void)` method of the `TwoWire` class returns `-1` on failed byte read.
=> fix(stdlib): fix `xod/i2c/read-byte` node error reading `0x00` value bug

workspace/__lib__/xod/core/equal(boolean)/patch.cpp, workspace/__lib__/xod/core/equal(boolean)/patch.xodp
This was requested on our forum.
The node is not only useful by itself, but also allows some generic nodes to work with boolean values.
=> Add equal(boolean)

packages/xod-arduino/platform/memory.h, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
It fixes #1866 and the bug reported on the [forum](https://forum.xod.io/t/xod-0-32-0-released-introducing-cloud-feeds/3006/2) (operator was added in arduino:avr 1.8.2).
=> Fix implementation of the placement new operator

packages/xod-arduino/platform/types.h, workspace/__ardulib__/Graphics/Canvas.h, workspace/__ardulib__/Graphics/Canvas.inl, workspace/__ardulib__/Graphics/Line.h, workspace/__ardulib__/Graphics/Line.inl, workspace/__ardulib__/Graphics/XGraphics.h, workspace/__ardulib__/Graphics/XGraphics.inl, workspace/__ardulib__/Graphics/XRender.h, workspace/__ardulib__/Graphics/XVector2.h, workspace/__ardulib__/README.md, workspace/__lib__/xod/color/color/patch.cpp, workspace/__lib__/xod/graphics/canvas/patch.cpp, workspace/__lib__/xod/graphics/canvas/patch.xodp, workspace/__lib__/xod/graphics/graphics/patch.cpp, workspace/__lib__/xod/graphics/graphics/patch.xodp, workspace/__lib__/xod/graphics/line-colored/patch.cpp, workspace/__lib__/xod/graphics/line-colored/patch.xodp, workspace/__lib__/xod/graphics/line/patch.cpp, workspace/__lib__/xod/graphics/line/patch.xodp, workspace/__lib__/xod/graphics/project.xod, workspace/big-patch/__fixtures__/arduino.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
- Introduce `xod/graphics` and ` __ardulib__ /Graphics` library basics.
- Add the `Line` graphic element.
- Add  `XColor()` struct constructors into the `packages/xod-arduino/platform/types.h`.
- Clang-format the `packages/xod-arduino/platform/types.h`.
- Update Fixtures.
=> XOD Graphics library basics

workspace/__ardulib__/Graphics/Point.h, workspace/__ardulib__/Graphics/Point.inl, workspace/__lib__/xod/graphics/line-colored/patch.xodp, workspace/__lib__/xod/graphics/line/patch.xodp, workspace/__lib__/xod/graphics/point-colored/patch.cpp, workspace/__lib__/xod/graphics/point-colored/patch.xodp, workspace/__lib__/xod/graphics/point/patch.cpp, workspace/__lib__/xod/graphics/point/patch.xodp
- Add the `Point` class to the `__ardulib__/Graphics/` and `xod/graphics` library.
- Correct `line` and `line-colored` nodes description.
=> Add the Point graphic primitive to the Graphic library.

.gitattributes
Removes`.bin` and `.hex` fixtures from github statistics and collapses еруь by default in PR previews.
=> Mark compiled fixtures as generated

workspace/__lib__/xod/graphics/pulse-on-change(graphics)/patch.cpp, workspace/__lib__/xod/graphics/pulse-on-change(graphics)/patch.xodp
Add the `pulse-on-change(graphics)` node into the `xod/core` library.
`pulse-on-change(graphics)` is necessary for the proper work of the `act` nodes inside quickstart display nodes.
=> Add the `pulse-on-change` node specialization for graphics.

workspace/__ardulib__/Graphics/XRender.h
The `lineBuffer` of the `renderScanlinePart` method should be `const`.
This issue was found in making the LCD display libraies.
=> Make the `lineBuffer` of the rendering process immutable.

workspace/__ardulib__/Graphics/XGraphics.inl
Fixed the boundary conditions for the canvas rendering process. There was an extra line.
This issue was found rendering the 1-pixel height canvas.
=> Fix the scanline boundary condition for the canvas rendering process.

workspace/__ardulib__/ST7735/XST7735.cpp, workspace/__lib__/xod-dev/st7735-display/st7735/patch.cpp
- Fix up the wrong `static_assert` for the `st7735` node, add the condition for the `255` default value of the `RST` port. 
- Fix the `_rst` port check at the `XST7735.cpp`. 
By now the "default" `RST` pin value is `D255`.
After complile it is `constexpr uint8_t PIN_VAL = 225` but not `D255`,  so the  `_rst == NOT_A_PIN` check is not working.
=> Fix up the RST pin conditions and the assertion in the ST7735 display library.

workspace/__lib__/xod/core/throttle/patch.cpp, workspace/test/test-core/test-throttle-numbers/patch.test.tsv
There is no issue, but I've found the bug while testing quick-start nodes for `ws2812`. Without this fix, `throttle` node returns the default value for the data type until the input values do not change.
Tabtests and consumer nodes keep working.
=> Fix throttle node: pass the constant values on setting up

CHANGELOG.md
* [ide] Extended support for the `color` type: a value can be entered as hex literal (like `#FACE8D`) or selected using a color picker widget (#1926, #1953)
* [c++] Move the `XColor` type definition from `xod/color/color` to the global `xod` scope (#1928)
* [core] Optimize the size of generated C++ code (#1925, #1943)
* [ide] Properly stop the running simulation session when opening a new project (#1924)
* [core] Fix a case when using bus nodes along with generic pins could break type casting (#1958)
* [nodes] Fix `xod/core/throttle` node that was ignoring incoming values at program starup (#1963)
* [xod/debug/tweak-color](https://xod.io/libs/xod/debug/tweak-color/) — Node for tweaking color values during debug or simulation sessions (#1942)
* …
=> Update changelog for the upcoming v0.33.0

bsconfig.json, packages/belt-holes/bsconfig.json, packages/belt-holes/package.json, packages/belt-holes/test/BeltHoles_List_jest.re, packages/xod-arduino/bsconfig.json, packages/xod-arduino/package.json, packages/xod-client-electron/package.json, packages/xod-func-tools/bsconfig.json, packages/xod-func-tools/package.json, packages/xod-func-tools/src/Either.re, packages/xod-func-tools/src/Errors.re, packages/xod-func-tools/src/Maybe.re, packages/xod-project/bsconfig.json, packages/xod-project/package.json, packages/xod-project/src/PatchPath.re, packages/xod-tabtest/bsconfig.json, packages/xod-tabtest/package.json, yarn.lock
There are a lot of new cool features:
https://bucklescript.github.io/blog/2019/11/18/whats-new-in-7
https://bucklescript.github.io/blog/2020/02/04/release-7-1-0
No reason to stay on older version.
=> Upgrade bs-platform to 7.1.1

packages/xod-client/src/core/styles/components/PointingPopup.scss, packages/xod-client/src/editor/components/inspectorWidgets/ColorPickerWidget.jsx, packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/ColorPinWidget.jsx
=> Fix positioning of the ColorPicker widget with right-sided Inspector

packages/xod-client/src/core/assets/index.html, packages/xod-client/src/core/styles/components/Editor.scss, packages/xod-client/src/core/styles/components/Inspector.scss, packages/xod-client/src/core/styles/components/ProjectBrowser.scss
There is no issue, but this is an old bug.
=> Fix scrolling of Project Browser and Inspector when they are alone in sidebar

workspace/__ardulib__/Graphics/XGraphics.inl, workspace/__ardulib__/ST7735/XST7735.h
- At the `XST7735.h` add the `ARDUINO_ARCH_ESP8266` condition, because ESP8266 has 4-byte ports.
- For ESP8266 math functions `min` and `max` both arguments must be explicitly specified of the same type - `max(int, int)`, `min(short int, short int)`. Added type casting to make expressions like `max(0, x)` or `min(y, 1)` compile.
=> Fix ST7735 and Graphics libs to be compatible with ESP8266 boards.

workspace/__ardulib__/ST7735/XST7735.cpp, workspace/__ardulib__/ST7735/XST7735.h, workspace/__lib__/xod-dev/st7735-display/rotate/patch.cpp, workspace/__lib__/xod-dev/st7735-display/rotate/patch.xodp
Add the `rotate` node that allows a user to change the display rotation.
Can be rotated in real-time;
0 degrees vertical position;
90 degrees horizontal position;
180 degrees vertical position;
270 degrees horizontal position.
=> Add the rotation of the screen for the ST7735 displays.

workspace/__ardulib__/README.md, workspace/__ardulib__/SSD1306/SSD1306.cpp, workspace/__ardulib__/SSD1306/SSD1306.h, workspace/__lib__/xod-dev/ssd1306-display/project.xod, workspace/__lib__/xod-dev/ssd1306-display/render/patch.cpp, workspace/__lib__/xod-dev/ssd1306-display/render/patch.xodp, workspace/__lib__/xod-dev/ssd1306-display/ssd1306-128x64-i2c-device/patch.cpp, workspace/__lib__/xod-dev/ssd1306-display/ssd1306-128x64-i2c-device/patch.xodp, workspace/__lib__/xod-dev/ssd1306-display/ssd1306-128x64-i2c/patch.xodp
XOD support of SSD1306 based monochrome I2C displays.
=> Support of SSD1306 based monochrome I2C displays

packages/xod-client/src/workers/wasm.worker.js
- It optimizes the performance of patterns like: `do { ... } while (millis() < timeout);`
For example, in the [worldtimeapi.xodball](https://github.com/xodio/xod/files/4627824/worldtimeapi.xodball.zip) the timer indicates a time to read the whole response from the server. It was about 33.5 seconds in the simulation, now it takes about 9.5 seconds. (3.5x faster).
Meanwhile, the same patch still works faster on the MCU, it takes about 4.5 seconds on Uno and ESP8266. 😞
- Replaces a no-op `delay` with something like a real delay, which blocks other code until the delay has ended up.
To test the example above, you need to cherry-pick this commit on top of the https://github.com/xodio/xod/tree/feat-1974-tethering-internet branch, which provides a tethering-inet. And use the staging server …
=> Pass millis() from JS into Simulation WASM

CHANGELOG.md
* [ide] Introduce [tethering internet](https://xod.io/docs/guide/tethering-inet) to provide internet to device/simulation via PC (#1979, #1985)
* [ide] Fix positioning of the ColorPicker widget when Inspector is docked to right (#1971)
* [ide] Fix scrolling of Project Browser and Inspector when they are the only section in a sidebar (#1972)
* [ide] Fix typos in the built-in tutorial. Thanks, @bartek-w! (#1990, #1991)
* [xod/graphics](https://xod.io/libs/xod/graphics) — a library to create graphics and graphic interfaces. Check out https://xod.io/docs/guide/#xod-graphics for details (#1988)
* [xod-dev/st7735-display](https://xod.io/libs/xod-dev/st7735-display) — support of ST7735 based TFT displays (#1988)
* [xod-dev/ssd1306-display](https://xod.io/libs/xod-dev/ssd1306-display) — support …
=> Update changelog for the upcoming v0.34.0

workspace/__ardulib__/WS2812_NoBufffer/WS2812.inl
The error caused by duplicating default values on arguments of `fill` and `fillPattern` methods in the implementation (`ws2812.inl` file), while it defined in the header file.
```
In file included from /var/folders/l3/68wttmkn0wz2wwc6knfbf9780000gn/T/xod_temp_sketchbookmPu8LH/libraries/WS2812_NoBufffer/WS2812.h:58:0,
from /var/folders/l3/68wttmkn0wz2wwc6knfbf9780000gn/T/xod_temp_sketchbookmPu8LH/xod_1591098769767_sketch/xod_1591098769767_sketch.ino:1131:
/var/folders/l3/68wttmkn0wz2wwc6knfbf9780000gn/T/xod_temp_sketchbookmPu8LH/libraries/WS2812_NoBufffer/WS2812.inl:165:75: error: default argument given for parameter 3 of 'void WS2812::fill(xod::XColor, uint32_t, bool)' [-fpermissive]
void WS2812::fill(XColor color, uint32_t pixelCount, bool fromTail = false) {
^
In file included from …
```
=> Fix compiling of WS2812 on ESP8266

packages/xod-arduino/src/templates.js
The bug was discovered by @yurybotov.
Here is a minimal example to reproduce the problem:
=> Fix an uncaught exception when transpiling a patch with a “dangling” defer node

.circleci/config.yml, packages/arduino-cli/README.md, packages/arduino-cli/src/config.js, packages/arduino-cli/src/index.js, packages/arduino-cli/src/optionParser.js, packages/arduino-cli/test-func/index.spec.js, packages/arduino-cli/test/optionParser.spec.js, packages/xod-cli/test-func/installArch.spec.js, packages/xod-deploy-bin/src/arduinoCli.js, tools/install-arduinocli.ps1
fixes #1896 
`yarn test-func` is still reporting some errors in the `xod-cli` package. Some of these are popping up in a simple `master` repository using the older arduino-cli binary. This leads me to believe that some errors are an issue with my environment.
=> Updating arduino-cli to 0.10

packages/xod-project/src/flatten.js, packages/xod-project/src/patchPathUtils.js, packages/xod-project/test/fixtures/cast-custom-types.xodball, packages/xod-project/test/flatten.spec.js
Problem: when the custom type node is nested behind the custom type terminal, the algorithm did not create a cast node.
A xodball to test some cases manually:
[cast-custom-types-orig.xodball.zip](https://github.com/xodio/xod/files/4972126/cast-custom-types-orig.xodball.zip)
=> Fix creating cast nodes for custom types

packages/xod-arduino/platform/uart.h, workspace/big-patch/__fixtures__/arduino.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
The problem was reported on the forum: https://forum.xod.io/t/nano-every-upload-issue/4198
=> Fix forward declaration of HardwareSerial for megaAVR architecture

workspace/__lib__/xod-dev/pn532-nfc/pn532-device/patch.cpp
Reported by @S-VIN.
`Adafruit-PN532` library depends on `Adafruit_BusIO` and won't compile without it.
=> Add missing dependency for xod-dev/pn532-nfc

workspace/__ardulib__/SSD1306/SSD1306.cpp, workspace/__ardulib__/SSD1306/SSD1306.h, workspace/__lib__/xod-dev/ssd1306-display/ssd1306-128x64-i2c-device/patch.cpp
Some problems were found working with the XOD graphics library and SSD1306 display for "UNO slot educations sets".
- Add `sendBuffer()` on device init to clear the screen.
- Fix ` SSD1306::renderScanlinePart(int16_t scanline, int16_t xmin, int16_t xmax, const uint16_t* lineBuffer)` wrong behaviour found moving the `canvas`.
- Replicate private `_sendCommand` for two and three arguments.
P.S. This lib still works horribly on weak controllers like Arduino Uno due to lack of memory 😢
Summoning @yurybotov
=> fix(stdlib) : ssd1306, fix `renderScanlinePart` behaviour

packages/xod-project/src/flatten.js, packages/xod-project/test/fixtures/cast-custom-types.xodball, packages/xod-project/test/flatten.spec.js
You can reproduce the bug by transpiling ("Show Code for Arduino") the `xod-dev/esp8266-mcu/example-get-data-from-dweet` patch.
Or you can create a minimal patch to reproduce the bug. Note, that there is a nested patch with a branch: one link directly to the output, another one — to the `format-color` node.
```
+-----------+
| color-hsl |
|           |
+-----O-----+
|
|
+-----O----------------+
|     |                |
|     +-------|        |
|     |     +-O------+ |
|     |     |        | |
|     |     | format | |
|     |     |        | |
|     |     +-O------+ |
|     |       |        |
|     |       |        |
+-----O-------O--------+
CLR      STR
```
=> Fix flatten: get rid of stale output custom type terminals

packages/xod-deploy-bin/src/arduinoCli.js, packages/xod-deploy-bin/src/constants.js
But we used this version by default because the latest release at that time had some critical bug.
Now the latest version works fine.
=> Use upstream ESP8266 package index instead of locked v2.4.3

workspace/__lib__/xod-dev/ws2812/example-pattern-police/patch.xodp, workspace/__lib__/xod/core/flip-n-times/patch.xodp, workspace/__lib__/xod/core/saw-wave-map/patch.xodp, workspace/__lib__/xod/core/saw-wave/patch.xodp, workspace/__lib__/xod/core/sine-wave-map/patch.xodp, workspace/__lib__/xod/core/sine-wave/patch.xodp, workspace/__lib__/xod/core/square-wave/patch.xodp, workspace/__lib__/xod/core/tri-wave-map/patch.xodp, workspace/__lib__/xod/core/tri-wave/patch.xodp, workspace/__lib__/xod/waves/dividable-timer/patch.cpp, workspace/__lib__/xod/waves/dividable-timer/patch.xodp, workspace/__lib__/xod/waves/example-1-frequency-modulation/patch.xodp, workspace/__lib__/xod/waves/example-2-peak-position/patch.xodp, workspace/__lib__/xod/waves/example-3-freeze/patch.xodp, workspace/__lib__/xod/waves/project.xod, workspace/__lib__/xod/waves/saw-wave/patch.xodp, workspace/__lib__/xod/waves/sine-wave-map/patch.xodp, workspace/__lib__/xod/waves/sine-wave/patch.xodp, workspace/__lib__/xod/waves/square-wave/patch.cpp, workspace/__lib__/xod/waves/square-wave/patch.xodp, workspace/__lib__/xod/waves/tri-wave-map/patch.cpp, workspace/__lib__/xod/waves/tri-wave-map/patch.xodp, workspace/__lib__/xod/waves/tri-wave/patch.xodp
and deprecate old *-wave nodes from xod/core:
`xod/core/saw-wave`
`xod/core/saw-wave-map`
`xod/core/sine-wave`
`xod/core/sine-wave-map`
`xod/core/square-wave`
`xod/core/tri-wave`
`xod/core/tri-wave-map`
=> Add xod/waves library

packages/xod-client/src/debugger/actions.js, packages/xod-client/src/debugger/containers/Log.jsx, packages/xod-client/src/debugger/reducer.js, packages/xod-client/src/editor/reducer.js, packages/xod-client/src/utils/components/Autoscroll.jsx, packages/xod-client/stories/Debugger.jsx
There is no issue, but there were some small bugs:
- if messages added to the log, but the log is hidden, then it might be opened not on the bottom and "Follow log" will be shown up from the beginning
- after clicking "Follow log" it sometimes does not follow it
- Clearing log did not start following the log
=> Fix follow log in Debugger pane

CHANGELOG.md
* [core] Introduce constant types and new C++ implementation syntax. (#2007)
* [core] Make color-type outputs bindable (#2011)
* [ide] Add ability to clone a patch from library to a local project (#1999, #2003)
* [nodes] Make `pulse-on-*` nodes behave consistently and not trigger on start (#2002)
* [core] Upgrade bundled arduino-cli to v0.12.0. Thanks, @quinkennedy! (#1986, #2012, #2029)
* [core] Use upstream ESP8266 package index instead of being locked to v2.4.3 (#2026)
* [core] Improved resolution of abstract nodes to allow specializations without the type suffix for types defined in the same library (#2004)
* [nodes] Unify interfaces of nodes in `xod-dev/esp8266`, `xod-dev/esp8266-mcu`, `xod-dev/w5500` and `xod/debug` to use abstract nodes from `xod/net` (#2004)
* [ide] Fix …
=> Update changelog for the upcoming v0.35.0

workspace/__lib__/xod/graphics/humidity-16x16-rgba/patch.cpp
=> Remove C++ typo in humidity icon implementation.

workspace/__lib__/xod/common-hardware/ds18b20-thermometer/patch.cpp
The issue was [reported on our forum](https://forum.xod.io/t/xod-35-0-soft-uart-fail/4413/4)
=> Fix typo in implementation of xod/common-hardware/ds18b20-thermometer

packages/xod-arduino/src/implementationGrammar.ne, packages/xod-arduino/test/fixtures/impl-basic.cpp, packages/xod-arduino/test/parseImplementation.spec.js
Makes identifiers that contain keywords `node`, `nodespace` and `meta` always parse as identifiers, not keywords.
=> Make sure implementation keywords are always detected correctly

packages/xod-arduino/platform/program.tpl.cpp, workspace/__lib__/xod/debug/get-local-ip/patch.cpp
=> Fix tethering inet

.prettierignore, packages/xod-deploy-bin/src/arduinoCli.js, workspace/__ardulib__/ESP32Servo/.gitignore, workspace/__ardulib__/ESP32Servo/README.md, workspace/__ardulib__/ESP32Servo/examples/Knob/Knob.ino, workspace/__ardulib__/ESP32Servo/examples/Multiple-Servo-Example-Arduino/Multiple-Servo-Example-Arduino.ino, workspace/__ardulib__/ESP32Servo/examples/PWMExample/PWMExample.ino, workspace/__ardulib__/ESP32Servo/examples/Sweep/Sweep.ino, workspace/__ardulib__/ESP32Servo/examples/ToneExample/ToneExample.ino, workspace/__ardulib__/ESP32Servo/examples/analogWriteExample/analogWriteExample.ino, workspace/__ardulib__/ESP32Servo/keywords.txt, workspace/__ardulib__/ESP32Servo/library.properties, workspace/__ardulib__/ESP32Servo/src/ESP32PWM.cpp, workspace/__ardulib__/ESP32Servo/src/ESP32PWM.h, workspace/__ardulib__/ESP32Servo/src/ESP32Servo.cpp, workspace/__ardulib__/ESP32Servo/src/ESP32Servo.h, workspace/__ardulib__/ESP32Servo/src/ESP32Tone.cpp, workspace/__ardulib__/ESP32Servo/src/ESP32Tone.h, workspace/__ardulib__/ESP32Servo/src/analogWrite.cpp, workspace/__ardulib__/ESP32Servo/src/analogWrite.h, workspace/__ardulib__/README.md, workspace/__lib__/xod-dev/servo/servo-device/patch.cpp, workspace/__lib__/xod/gpio/pwm-write/patch.cpp, workspace/big-patch/__fixtures__/arduino.cpp
This PR includes:
- fix of adding new URLs into `extra.txt`: updated arduino-cli returns "ENOENT" code instead of `6` when JSON file is not found and our `catch` does not work as expected. This bug does not break a loading new file, but it shows an error message, and list of boards appears only after clicking "Update" button or opening of the upload popup next time.
- Bundle https://github.com/madhephaestus/ESP32Servo library into desktop IDE to support PWM and Servos without requiring libraries from the internet
- Tweak `xod-dev/servo/servo-device` and `xod/gpio/pwm-write` to use the bundled library and work fine on ESP32
=> Support esp32 boards

packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
Some time ago, when we refactor widgets, we'd lost a method `updateValue` of `Widget` class.
Now it's back and these hotkeys will work again:
- Escape button to cancel changes
- Arrow keys (optionally with shift key) to change numbers
=> Fix hotkeys in Inspector Pin widgets

packages/xod-arduino/src/formatTweakMessage.js, packages/xod-project/src/utils.js
=> Fix tweak-bytes: make possible to use char literals in live session

packages/xod-client/src/core/styles/components/CppPatchDocs.scss, packages/xod-client/src/editor/components/CppPatchDocs.jsx, packages/xod-project/src/utils.js
=> Add information about constants in C++ Cheatsheet (sidebar)

packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/src/templates.js
It fixes #2047 
The bug was introduced in the 0.33.0 right in the commit https://github.com/xodio/xod/commit/0880f41e252d8e000ade77b5efdb65d28857eba3 😬
=> Fix dirtyness propagation optimization to work fine with tweaks

workspace/__lib__/xod-dev/esp8266-mcu/lan-ip/patch.cpp
The issue was reported on [our forum](https://forum.xod.io/t/lan-ip-is-not-compiling/4470)
=> Fix `xod-dev/esp8266-mcu/lan-ip` implementation

workspace/__ardulib__/Graphics/Bitmap.h
This bug was found here: https://forum.xod.io/t/graphics-arduino-due-st7735/4411
=> fix(stdlib): make xod graphics bitmaps compile on non-avr boards

.circleci/config.yml, packages/xod-arduino/platform/patchContext.tpl.cpp, packages/xod-arduino/platform/program.tpl.cpp, packages/xod-arduino/src/Directives.re, packages/xod-arduino/src/Directives.rei, packages/xod-arduino/src/Directives_Js.re, packages/xod-arduino/src/templates.js, packages/xod-arduino/src/transpiler.js, packages/xod-arduino/src/types.js, packages/xod-arduino/tools/test-avr-size.sh, packages/xod-client/src/editor/codemirrorXodMode.js, workspace/__lib__/xod/core/animation-unit/patch.cpp, workspace/__lib__/xod/core/continuously-pausable/patch.cpp, workspace/__lib__/xod/core/continuously/patch.cpp, workspace/__lib__/xod/core/defer(boolean)/patch.cpp, workspace/__lib__/xod/core/defer(byte)/patch.cpp, workspace/__lib__/xod/core/defer(number)/patch.cpp, workspace/__lib__/xod/core/defer(pulse)/patch.cpp, workspace/__lib__/xod/core/defer(string)/patch.cpp, workspace/__lib__/xod/debug/is-receiving/patch.cpp, workspace/__lib__/xod/debug/stream-string/patch.cpp, workspace/__lib__/xod/gpio/analog-read/patch.cpp, workspace/__lib__/xod/mutex/mutex-state/patch.cpp, workspace/big-patch/__fixtures__/arduino.cpp, workspace/blink/__fixtures__/arduino.cpp, workspace/count-with-feedback-loops/__fixtures__/arduino.cpp, workspace/dht-pack-unpack/__fixtures__/arduino.cpp, workspace/lcd-time/__fixtures__/arduino.cpp, workspace/two-button-switch/__fixtures__/arduino.cpp
Before, we used `setTimeout(0, ctx)` to schedule evaluation of a node as soon as possible.
But it would only mark node as dirty on the next millisecond and generate some unnecessary code.
`setImmediate` is a new API for this particular case that works faster, generates less code and occupies less RAM.
=> Introduce setImmediate API

packages/xod-client-browser/src/containers/App.jsx, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/core/containers/App.jsx, packages/xod-client/src/editor/containers/Editor.jsx, packages/xod-client/src/utils/browser.js
It fixes #1737 
It includes:
- moving hotkeys from `Editor` to `App` component
- auto-focus on the `App` element on startup
- capture `focusout` events and in case that focus moved to the body (focused element was deleted) focus to the `App` component
=> Ensure hotkeys work fine

packages/xod-client/src/core/styles/components/Node.scss, packages/xod-client/src/project/components/nodeParts/BusNodeBody.jsx
It closes #1721.
Meet the new look of bus nodes:
Please, check it out, try to drag, select nodes, try to overlap some nodes, and then drag it to other places and etc.
=> Restyle bus nodes to avoid misclicks

packages/xod-client/src/editor/utils.js
It closes #1441 
Previously, the position for pasted nodes calculates only by pins. This PR takes into account a node width, which might be changed on such nodes as constants, watches, tweaks.
=> Paste expanded nodes to the right position

packages/xod-client-browser/src/containers/App.jsx, packages/xod-client-electron/src/view/containers/App.jsx, packages/xod-client/src/utils/constants.js, packages/xod-client/src/utils/menu.js
It closes #2072 
I choose `Ctrl+U` and `Ctrl+Shift+U` hotkeys to open the popup. I decided to use a `Shift` modifier because this hotkey opens the same popup.
Also, there was a hotkey to toggle the debug pane: `Ctrl+Shift+U`. So I've replaced it with `Ctrl+D`.
=> Add hotkeys to show upload popup

.circleci/config.yml
Install NodeJS `v10.13.0` on MacOS CircleCI runner via `nvm`. `v10.13.0` is the version, that used in Docker CircleCI runner and the minimal NodeJS version for #2074 build. Adds 10-15s.
=> tweak(circleci): pin node version on macos

packages/xod-cli/src/commands/boards.js, packages/xod-cli/src/listrTasks.js, packages/xod-client-electron/src/app/arduinoCli.js, packages/xod-deploy-bin/package.json, packages/xod-deploy-bin/src/arduinoCli.js
It fixes a couple of bugs:
1. Open the XOD IDE first time (clean App data, delete workspace)
2. Click "Upload to Arduino"
Everything works as usual.
The error message "Package Index Broken: Unexpected end of JSON input" appeared in the snack bar. The list of boards is empty. Will appear if you open the upload popup again or click the "Update" button.
1. Open the XOD IDE
2. Delete the workspace directory
3. Click "Upload to Arduino" button
Upload popup appeared, there is a list of the boards in the select box.
No boards in the select box are listed.
Also, the error "ENOENT ... extra.txt file" appears in the snack bar.
=> Fix workspace errors when user deleted a workspace

CHANGELOG.md
* [ide] Make deployment pane resizable (#2081)
* [ide] Copy and save logs from deployment pane (#2078, #2079)
* [ide] Recover IDE from runtime exceptions (#2074)
* [ide] Add hotkeys to show upload popup (#2073)
* [ide] Show a favicon in the browser IDE (#2070)
* [ide] Restyle bus nodes to avoid misclicks (#2069)
* [ide] Add hotkeys to create terminal(`t`), constant(`c`), tweak and watch(`w`) nodes while linking (#2068)
* [ide] Focus on label editor in Inspector when double-clicking terminal or bus nodes (#2063)
* [ide] Move to Electron v10, node.js v12 (#2084)
* [ide] Fix workspace errors when user deleted a workspace (#2082)
* [ide] Paste "expanded" nodes (such as constants, watches, tweaks) to the right position (#2071)
* [ide] Fix hotkeys not working in some cases (#2067)
* [ide] Show …
=> Update changelog for the upcoming v0.37.0

packages/xod-client-electron/src/app/main.js, packages/xod-client-electron/src/app/settings.js, packages/xod-client-electron/src/app/utils.js
There is no issue 😬 
Updating of the electron also causes an update of the `electron-settings` package. The newer version of this package changed the default name of the settings file. To keep user settings we've changed the filename, but only in the main process. So it produced a bug when the user compile&upload something with third-party C++ libraries — the libraries from his workspace does not copy if he set a workspace in the custom (not default) path.
On loading/saving settings we always set the path and file name for the settings file (for both kinds of processes).
=> Fix: configure electron-settings for all kinds of processes

workspace/welcome-to-xod/104-button/patch.xodp, workspace/welcome-to-xod/108-text-lcd/patch.xodp, workspace/welcome-to-xod/110-ldr/patch.xodp
Fixes https://github.com/xodio/xod-docs/issues/219 and a couple of other minor issues.
=> Fix minor mistakes in welcome-to-xod project

packages/xod-client/src/core/styles/components/AttachmentEditor.scss, packages/xod-client/src/core/styles/components/CodeMirror.scss
=> Fix scroll in cpp editor

packages/xod-arduino/src/transpiler.js, packages/xod-client/src/debugger/selectors.js, packages/xod-client/src/debugger/utils.js, packages/xod-client/src/editor/actions.js, packages/xod-client/src/project/components/Node.jsx, packages/xod-client/src/project/components/nodeParts/TableLogNodeBody.jsx, packages/xod-client/test/tableLogSources.spec.js, packages/xod-project/src/constants.js, workspace/__lib__/xod/debug/arity-aware-join/patch.cpp, workspace/__lib__/xod/debug/arity-aware-join/patch.xodp, workspace/__lib__/xod/debug/table-log/patch.xodp, workspace/__lib__/xod/debug/tsv-join/patch.xodp, workspace/__lib__/xod/debug/tsv-log/patch.cpp, workspace/__lib__/xod/debug/tsv-log/patch.xodp
It includes:
1. A few new utility nodes in `xod/debug` and restyled `table-log`, which is a variadic-pass (no more `join` on the user-side).
2. Tweaks in `xod-arduino` and `xod-client` to keep the behavior of nodes and table log tab as it was before: no excessive labels in the sources dropdown, show collected data on the `table-log`, open correct source by double-clicking on the `table-log` node.
=> Add sugar to table log feature
